#!/bin/sh

busybox killall bluealsa-aplay 

busybox killall bluealsa

bluealsa -p hfp-hf &

arecord -Dhw:1,0 -r 8000 -c 2 -f S16_LE |aplay -Dhw:0,0 -r 8000 -c 2 -f S16_LE &

arecord -D 2mic_loopback -r 8000 -f S16_LE -c 2 --period-size 128 --buffer-size 65536|aplay -D hw:1,0 -r 8000 -c 2 -f S16_LE &