#!/bin/sh

busybox killall bluealsa-aplay 

busybox killall bluealsa

bluealsa -p hfp-hf &

echo ATA | bluealsa-rfcomm --hci=hci0 $( hcitool con | sed -n 2p |busybox tr -d "\n" | busybox cut -b 8-25)

arecord -Dhw:1,0 -r 8000 -c 2 -f S16_LE |aplay -Dhw:0,0 -r 8000 -c 2 -f S16_LE

arecord -Dhw:0,0 -r 8000 -f S16_LE -c 2 |aplay -D hw:0,1 -r 8000 -c 2 -f S16_LE