#define XCAM_VERSION 1
typedef enum _XCAM_HANDLER_TYPE {
    XCAM_HANDLER_3A,
    XCAM_HANDLER_AE,
    XCAM_HANDLER_AWB,
    XCAM_HANDLER_AF,
    XCAM_HANDLER_COMMON
} XCAM_HANDLER_TYPE;
#define VERSION "1.0"
