option('arch', type: 'combo', choices: ['auto', 'arm', 'armv7l', 'armhf', 'arm32', 'armv8', 'arm64', 'aarch64'],
       description: 'arch (default: auto)')
option('library', type: 'string', value: '',
       description: 'library path (default: <null>)')
option('gpu', type: 'string', value: 'valhall-g610',
       description: 'GPU name (default: valhall-g610)')
option('platform', type: 'string', value: '',
       description: 'Required platform (default: <null>)')
option('opencl-icd', type: 'boolean', value: true,
       description: 'OpenCL Installable Client Driver (ICD) (default: true)')
option('khr-header', type: 'boolean', value: false,
       description: 'Install KHR header (default: false)')
option('vendor-package', type: 'boolean', value: false,
       description: 'Install as vendor package (default: false)')
option('hooks', type: 'boolean', value: true,
       description: 'Enable hook library (default: true)')
option('wrappers', type: 'boolean', value: true,
       description: 'Install with wrappers (default: true)')

option('version', type: 'string', value: '',
       description: 'deprecated')
option('subversion', type: 'string', value: '',
       description: 'deprecated')
option('wayland-egl', type: 'boolean', value: false,
       description: 'deprecated')
option('with-overlay', type: 'boolean', value: false,
       description: 'deprecated')
option('firmware-dir', type: 'string', value: '',
       description: 'deprecated')
