/******************************************************************************
 *
 * Copyright 2019, Fuzhou Rockchip Electronics Co.Ltd . All rights reserved.
 * No part of this work may be reproduced, modified, distributed, transmitted,
 * transcribed, or translated into any language or computer format, in any form
 * or by any means without written permission of:
 * Fuzhou Rockchip Electronics Co.Ltd .
 *
 *
 *****************************************************************************/
/**
 * @file    calibtags.h
 *
 *
 *****************************************************************************/
#ifndef __CALIB_TAGS_H__
#define __CALIB_TAGS_H__

#include "ebase/types.h"
#include "xmltags.h"


/******************************************************************************
 * XML tag attributes
 *****************************************************************************/
#define CALIB_ATTRIBUTE_TYPE                                "type"
#define CALIB_ATTRIBUTE_TYPE_CHAR                           "char"
#define CALIB_ATTRIBUTE_TYPE_DOUBLE                         "double"
#define CALIB_ATTRIBUTE_TYPE_STRUCT                         "struct"
#define CALIB_ATTRIBUTE_TYPE_CELL                           "cell"

#define CALIB_ATTRIBUTE_SIZE                                "size"
#define CALIB_ATTRIBUTE_SIZE_FORMAT                         "[%d %d]"
#define CALIB_ATTRIBUTE_SIZE_NO_ELEMENTS                    2

#define CALIB_ATTRIBUTE_INDEX                               "index"


/******************************************************************************
 * XML tag name type
 *****************************************************************************/
 
//isp output is color, gray or mixture
#define CALIB_HEADER_ISP_OUTPUT_COLOR_TYPE_TAG					   "color"
#define CALIB_HEADER_ISP_OUTPUT_GRAY_TYPE_TAG					   "gray"
#define CALIB_HEADER_ISP_OUTPUT_MIXTURE_TYPE_TAG				  "mixture"


// awb version name
#define CALIB_SENDOR_AWB_VERSION_10_NAME_TAG						"VERSION_10"
#define CALIB_SENDOR_AWB_VERSION_11_NAME_TAG						"VERSION_11"


// awb door type
#define CALIB_SENSOR_AWB_ILLUMINATION_DOOR_TYPE_INDOOR              "INDOOR"
#define CALIB_SENSOR_AWB_ILLUMINATION_DOOR_TYPE_OUTDOOR             "OUTDOOR"


// awb type
#define CALIB_SENSOR_AWB_ILLUMINATION_AWB_TYPE_MANUAL               "MANUAL"
#define CALIB_SENSOR_AWB_ILLUMINATION_AWB_TYPE_AUTO                 "AUTO"


// hist measur mode
#define CALIB_SENSOR_AEC_CAMERICISPHISTMODE_R               "R"//cxf
#define CALIB_SENSOR_AEC_CAMERICISPHISTMODE_G               "G"//cxf
#define CALIB_SENSOR_AEC_CAMERICISPHISTMODE_B               "B"//cxf
#define CALIB_SENSOR_AEC_CAMERICISPHISTMODE_RGB             "RGB"//cxf
#define CALIB_SENSOR_AEC_CAMERICISPHISTMODE_Y               "Y"//cxf


// aec measure mode
#define CALIB_SENSOR_AEC_CAMERICISPEXPMEASURINGMODE_1       "Y"//cxf
#define CALIB_SENSOR_AEC_CAMERICISPEXPMEASURINGMODE_2       "RGB"//cxf


//aec hdr ctrl mode
#define CALIB_SENSOR_HDRCTRL_MODE_DCG "DCG"
#define CALIB_SENSOR_HDRCTRL_MODE_STAGGER "STAGGER"


//dpcc register name
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_MODE            "ISP_DPCC_MODE"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_OUTPUT_MODE     "ISP_DPCC_OUT_MODE"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_SET_USE         "ISP_DPCC_SET_USE"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_METHODS_SET_1   "ISP_DPCC_METHODS_SET1"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_METHODS_SET_2   "ISP_DPCC_METHODS_SET2"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_METHODS_SET_3   "ISP_DPCC_METHODS_SET3"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_LINE_THRESH_1   "ISP_DPCC_LINE_THRESH_1"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_LINE_MAD_FAC_1  "ISP_DPCC_LINE_MAD_FAC_1"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_PG_FAC_1        "ISP_DPCC_PG_FAC_1"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_RND_THRESH_1    "ISP_DPCC_RND_THRESH_1"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_RG_FAC_1        "ISP_DPCC_RG_FAC_1"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_LINE_THRESH_2   "ISP_DPCC_LINE_THRESH_2"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_LINE_MAD_FAC_2  "ISP_DPCC_LINE_MAD_FAC_2"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_PG_FAC_2        "ISP_DPCC_PG_FAC_2"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_RND_THRESH_2    "ISP_DPCC_RND_THRESH_2"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_RG_FAC_2        "ISP_DPCC_RG_FAC_2"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_LINE_THRESH_3   "ISP_DPCC_LINE_THRESH_3"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_LINE_MAD_FAC_3  "ISP_DPCC_LINE_MAD_FAC_3"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_PG_FAC_3        "ISP_DPCC_PG_FAC_3"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_RND_THRESH_3    "ISP_DPCC_RND_THRESH_3"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_RG_FAC_3        "ISP_DPCC_RG_FAC_3"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_RO_LIMITS       "ISP_DPCC_RO_LIMITS"
#define CALIB_SENSOR_DPCC_REGISTER_ISP_DPCC_RND_OFFS        "ISP_DPCC_RND_OFFS"


//3dnr 5x5 weight for parse
#define CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_WEIGHT_TAG  "luma_w"
#define CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_WEIGHT_TAG  "chrm_w"
#define CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_WEIGHT_TAG  "src_shp_w"



// should expand non leaf node's tags
typedef enum CALIB_IQ_TAG_ID_E 
{
	/******************************************************************************
	* XML main section
	*****************************************************************************/
	CALIB_FILESTART_TAG_ID,

	/******************************************************************************
	* XML cell section
	*****************************************************************************/
	CALIB_CELL_TAG_ID,

	/******************************************************************************
	* XML header section
	*****************************************************************************/
	CALIB_HEADER_TAG_ID,
	CALIB_HEADER_CREATION_DATE_TAG_ID,
	CALIB_HEADER_CREATOR_TAG_ID,
	CALIB_HEADER_SENSOR_NAME_TAG_ID,
	CALIB_HEADER_SAMPLE_NAME_TAG_ID,
	CALIB_HEADER_GENERATOR_VERSION_TAG_ID,
	CALIB_HEADER_CODE_XML_PARSE_VERSION_TAG_ID,
	CALIB_HEADER_ISP_OUTPUT_TYPE_TAG_ID,
	CALIB_HEADER_SDK_IQ_VERIFY_ID,

	/******************************************************************************
	* XML resolution tag
	*****************************************************************************/
	CALIB_HEADER_RESOLUTION_TAG_ID,
	CALIB_HEADER_RESOLUTION_NAME_TAG_ID,
	CALIB_HEADER_RESOLUTION_ID_TAG_ID,
	CALIB_HEADER_RESOLUTION_WIDTH_TAG_ID,
	CALIB_HEADER_RESOLUTION_HEIGHT_TAG_ID,
	CALIB_HEADER_RESOLUTION_FRATE_TAG_ID,
	CALIB_HEADER_RESOLUTION_FRATE_NAME_TAG_ID,
	CALIB_HEADER_RESOLUTION_FRATE_FPS_TAG_ID,

	CALIB_SENSOR_TAG_ID,

	/******************************************************************************
	* XML sensor AWB tag
	*****************************************************************************/
	CALIB_SENSOR_AWB_TAG_ID,
	CALIB_SENSOR_AWB_VALID_VERSION_NAME_TAG_ID,
	CALIB_SENSOR_AWB_VERSION_10_TAG_ID,


	/******************************************************************************
	* XML sensor AWB V10 golbal tag
	*****************************************************************************/ 
	CALIB_SENSOR_AWB_V10_GLOBALS_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_NAME_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_RESOLUTION_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_SVDMEANVALUE_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_PCAMATRIX_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_CENTERLINE_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_RG2_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_MAXDIST2_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_RG1_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_MAXDIST1_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_GLOBALFADE2_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_GLOBALGAINDIST2_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_GLOBALFADE1_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_GLOBALGAINDIST1_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_KFACTOR_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_FADE2_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_CB_MIN_REGIONMAX_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_CR_MIN_REGIONMAX_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_MAX_CSUM_REGIONMAX_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_CB_MIN_REGIONMIN_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_CR_MIN_REGIONMIN_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_MAX_CSUM_REGIONMIN_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_MINC_REGIONMAX_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_MAXY_REGIONMAX_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_MINY_MAXG_REGIONMAX_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_MINC_REGIONMIN_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_MAXY_REGIONMIN_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_MINY_MAXG_REGIONMIN_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_REFCB_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_REFCR_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_REGION_SIZE_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_REGION_SIZE_INC_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_REGION_SIZE_DEC_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_RGPROJ_INDOOR_MIN_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_RGPROJ_MAX_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_RGPROJ_MAX_SKY_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_RGPROJ_OUTDOOR_MIN_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_RGPROJ_YELLOW_LIMIT_ENABLE_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_RGPROJ_A_LIMIT_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_RGPROJ_A_WEIGHT_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_RGPROJ_YELLOW_LIMIT_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_RGPROJ_ILL_TO_CWF_ENABLE_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_RGPROJ_ILL_TO_CWF_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_RGPROJ_ILL_TO_CWF_WEIGHT_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_CLIP_OUTDOOR_ID,


	/******************************************************************************
	* XML sensor AWB v10 IIR tag
	*****************************************************************************/ 
	CALIB_SENSOR_AWB_V10_GLOBALS_IIR_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_IIR_DAMP_COEF_ADD_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_IIR_DAMP_COEF_SUB_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_IIR_DAMP_FILTER_THRESHOLD_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_IIR_DAMPING_COEF_MIN_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_IIR_DAMPING_COEF_MAX_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_IIR_DAMPING_COEF_INIT_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_IIR_EXP_PRIOR_FILTER_SIZE_MAX_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_IIR_EXP_PRIOR_FILTER_SIZE_MIN_TAG_ID,
	CALIB_SENSOR_AWB_V10_GLOBALS_IIR_EXP_PRIOR_MIDDLE_TAG_ID,

	/******************************************************************************
	* XML sensor AWB  V10 ILLUMINATION tag
	*****************************************************************************/ 
	CALIB_SENSOR_AWB_V10_ILLUMINATION_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_NAME_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_DOOR_TYPE_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_GMM_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_GMM_INV_COV_MATRIX_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_GMM_GAUSSIAN_SFACTOR_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_GMM_GAUSSIAN_MVALUE_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_GMM_TAU_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_ALSC_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_ALSC_RES_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_ALSC_RES_LSC_PROFILE_LIST_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_MANUAL_WB_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_MANUAL_CC_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_MANUAL_CTO_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_AWB_TYPE_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_SAT_CT_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_SAT_CT_GAIN_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_SAT_CT_SAT_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_VIG_CT_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_VIG_CT_GAIN_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_VIG_CT_VIG_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_ACC_TAG_ID,
	CALIB_SENSOR_AWB_V10_ILLUMINATION_ACC_CC_PROFILE_LIST_TAG_ID,


	CALIB_SENSOR_AWB_VERSION_11_TAG_ID,


	/******************************************************************************
	* XML sensor AWB V11 golbal tag
	*****************************************************************************/
	CALIB_SENSOR_AWB_V11_GLOBALS_TAG_ID,
	CALIB_SENSOR_AWB_V11_GLOBALS_GAIN_CLIP_ENABLE_TAG_ID,
	CALIB_SENSOR_AWB_V11_GLOBALS_MAX_CSUM_BR_TAG_ID,
	CALIB_SENSOR_AWB_V11_GLOBALS_MAX_CSUM_SR_TAG_ID,
	CALIB_SENSOR_AWB_V11_GLOBALS_MINC_BR_TAG_ID,
	CALIB_SENSOR_AWB_V11_GLOBALS_MAXY_BR_TAG_ID,
	CALIB_SENSOR_AWB_V11_GLOBALS_MINY_BR_TAG_ID,
	CALIB_SENSOR_AWB_V11_GLOBALS_MINC_SR_TAG_ID,
	CALIB_SENSOR_AWB_V11_GLOBALS_MAXY_SR_TAG_ID,
	CALIB_SENSOR_AWB_V11_GLOBALS_MINY_SR_TAG_ID,


	/******************************************************************************
	* XML sensor AWB  V11 ILLUMINATION tag
	*****************************************************************************/ 
	CALIB_SENSOR_AWB_V11_ILLUMINATION_TAG_ID,
	CALIB_SENSOR_AWB_V11_ILLUMINATION_REFERENCE_GAIN_TAG_ID,


	/******************************************************************************
	 * XML LSC section
	 *****************************************************************************/
	CALIB_SENSOR_LSC_TAG_ID,
	CALIB_SENSOR_LSC_PROFILE_NAME_TAG_ID,
	CALIB_SENSOR_LSC_PROFILE_RESOLUTION_TAG_ID,
	CALIB_SENSOR_LSC_PROFILE_ILLUMINATION_TAG_ID,
	CALIB_SENSOR_LSC_PROFILE_LSC_SECTORS_TAG_ID,
	CALIB_SENSOR_LSC_PROFILE_LSC_NO_TAG_ID,
	CALIB_SENSOR_LSC_PROFILE_LSC_XO_TAG_ID,
	CALIB_SENSOR_LSC_PROFILE_LSC_YO_TAG_ID,
	CALIB_SENSOR_LSC_PROFILE_LSC_SECTOR_SIZE_X_TAG_ID,
	CALIB_SENSOR_LSC_PROFILE_LSC_SECTOR_SIZE_Y_TAG_ID,
	CALIB_SENSOR_LSC_PROFILE_LSC_VIGNETTING_TAG_ID,
	CALIB_SENSOR_LSC_PROFILE_LSC_SAMPLES_RED_TAG_ID,
	CALIB_SENSOR_LSC_PROFILE_LSC_SAMPLES_GREENR_TAG_ID,
	CALIB_SENSOR_LSC_PROFILE_LSC_SAMPLES_GREENB_TAG_ID,
	CALIB_SENSOR_LSC_PROFILE_LSC_SAMPLES_BLUE_TAG_ID,


	/******************************************************************************
	 * XML CC section
	 *****************************************************************************/
	CALIB_SENSOR_CC_TAG_ID,
	CALIB_SENSOR_CC_PROFILE_NAME_TAG_ID,
	CALIB_SENSOR_CC_PROFILE_SATURATION_TAG_ID,
	CALIB_SENSOR_CC_PROFILE_CC_MATRIX_TAG_ID,
	CALIB_SENSOR_CC_PROFILE_CC_OFFSETS_TAG_ID,
	CALIB_SENSOR_CC_PROFILE_WB_TAG_ID,


	/******************************************************************************
	 * XML AF section
	 *****************************************************************************/
	CALIB_SENSOR_AF_TAG_ID,
	CALIB_SENSOR_AF_WINDOW_NUM_TAG_ID,
	CALIB_SENSOR_AF_WINDOW_A_TAG_ID,
	CALIB_SENSOR_AF_WINDOW_B_TAG_ID,
	CALIB_SENSOR_AF_WINDOW_C_TAG_ID,
	CALIB_SENSOR_AF_CONTRAST_AF_TAG_ID,
	CALIB_SENSOR_AF_LASER_AF_TAG_ID,
	CALIB_SENSOR_AF_PDAF_TAG_ID,
	//WINDOW
	CALIB_SENSOR_AF_H_OFFS_TAG_ID,
	CALIB_SENSOR_AF_V_OFFS_TAG_ID,
	CALIB_SENSOR_AF_H_SIZE_TAG_ID,
	CALIB_SENSOR_AF_V_SIZE_TAG_ID,
	//CONTRAST 
	CALIB_SENSOR_AF_CONTRAST_ENABLE_TAG_ID,
	CALIB_SENSOR_AF_SEARCH_STRATEGY_TAG_ID,
	CALIB_SENSOR_AF_FULL_DIR_TAG_ID,
	CALIB_SENSOR_AF_FULL_RANGE_TBL_TAG_ID,
	CALIB_SENSOR_AF_ADAPTIVE_DIR_TAG_ID,
	CALIB_SENSOR_AF_ADAPTIVE_RANGE_TBL_TAG_ID,
	
	CALIB_SENSOR_AF_TRIG_THERS_TAG_ID,
	CALIB_SENSOR_AF_TRIG_VALUE_TAG_ID,
	CALIB_SENSOR_AF_TRIG_FRAMES_TAG_ID,
	CALIB_SENSOR_AF_TRIG_ANTI_FLASH_TAG_ID,
	
	CALIB_SENSOR_AF_FINISH_THERS_MAIN_TAG_ID,
	CALIB_SENSOR_AF_FINISH_THERS_SUB_TAG_ID,
	CALIB_SENSOR_AF_FINISH_THERS_OFFSET_TAG_ID,
	
	CALIB_SENSOR_AF_STABLE_THERS_TAG_ID,
	CALIB_SENSOR_AF_STABLE_VALUE_TAG_ID,
	CALIB_SENSOR_AF_STABLE_FRAMES_TAG_ID,
	CALIB_SENSOR_AF_STABLE_TIME_TAG_ID,
	CALIB_SENSOR_AF_OUT_FOCUS_VALUE_TAG_ID,
	CALIB_SENSOR_AF_OUT_FOCUS_LUMA_TAG_ID,
	CALIB_SENSOR_AF_OUT_FOCUS_POS_TAG_ID,
	//LASER 
	CALIB_SENSOR_AF_LASERAF_ENABLE_TAG_ID,
	CALIB_SENSOR_AF_LASER_AF_VCMDOT_TAG_ID,
	CALIB_SENSOR_AF_LASER_AF_DISTANCEDOT_TAG_ID,
	//pdaf
	CALIB_SENSOR_AF_PDAF_ENABLE_TAG_ID,

	/******************************************************************************
	 * XML AEC section
	 *****************************************************************************/
	CALIB_SENSOR_AEC_TAG_ID,
	CALIB_SENSOR_AEC_SETPOINT_TAG_ID,
	CALIB_SENSOR_AEC_NIGHT_SETPOINT_TAG_ID,
	CALIB_SENSOR_AEC_CLM_TOLERANCE_TAG_ID,
	CALIB_SENSOR_AEC_DAMP_OVER_TAG_ID,
	CALIB_SENSOR_AEC_DAMP_UNDER_TAG_ID,
	CALIB_SENSOR_AEC_DAMP_OVER_VIDEO_TAG_ID,
	CALIB_SENSOR_AEC_DAMP_UNDER_VIDEO_TAG_ID,
	CALIB_SENSOR_AEC_AFPS_MAX_GAIN_TAG_ID,

	CALIB_SENSOR_AEC_ECM_TAG_ID,
	CALIB_SENSOR_AEC_ECM_NAME_TAG_ID,
	CALIB_SENSOR_AEC_ECM_SCHEMES_TAG_ID,
	CALIB_SENSOR_AEC_ECM_SCHEME_NAME_TAG_ID,
	CALIB_SENSOR_AEC_ECM_SCHEME_OFFSETT0FAC_TAG_ID,
	CALIB_SENSOR_AEC_ECM_SCHEME_SLOPEA0_TAG_ID,
	
	CALIB_SENSOR_AEC_GAINRANGE_TAG_ID,
	CALIB_SENSOR_AEC_GRIDWEIGHTS_TAG_ID,
	CALIB_SENSOR_AEC_NIHGT_GRIDWEIGHTS_TAG_ID,
	CALIB_SENSOR_AEC_TIMEFACTOR_TAG_ID,
	CALIB_SENSOR_AEC_CAMERICISPHISTMODE_TAG_ID,
	CALIB_SENSOR_AEC_CAMERICISPEXPMEASURINGMODE_TAG_ID,

	CALIB_SENSOR_AEC_DYNAMIC_SETPOINT_TAG_ID,
	CALIB_SENSOR_AEC_DYNAMIC_SETPOINT_NAME_TAG_ID,
	CALIB_SENSOR_AEC_DYNAMIC_SETPOINT_ENABLE_TAG_ID,
	CALIB_SENSOR_AEC_DYNAMIC_SETPOINT_EXPVALUE_TAG_ID,
	CALIB_SENSOR_AEC_DYNAMIC_SETPOINT_DYSETPOINT_TAG_ID,

	//exopsure separate
	CALIB_SENSOR_AEC_EXP_SEPARATE_TAG_ID,
	CALIB_SENSOR_AEC_EXP_SEPARATE_NAME_TAG_ID,
	CALIB_SENSOR_AEC_EXP_SEPARATE_TIMEDOT_TAG_ID,
	CALIB_SENSOR_AEC_EXP_SEPARATE_GAINDOT_TAG_ID,
	CALIB_SENSOR_AEC_EXP_SEPARATE_LTIMEDOT_TAG_ID,
	CALIB_SENSOR_AEC_EXP_SEPARATE_STIMEDOT_TAG_ID,
	CALIB_SENSOR_AEC_EXP_SEPARATE_LGAINDOT_TAG_ID,
	CALIB_SENSOR_AEC_EXP_SEPARATE_SGAINDOT_TAG_ID,
	//fps set config
	CALIB_SENSOR_AEC_FPS_FPS_SET_CONFIG_TAG_ID,
	CALIB_SENSOR_AEC_FPS_FPS_SET_ENABLE_TAG_ID,
	CALIB_SENSOR_AEC_FPS_IS_FPS_FIX_TAG_ID,
	CALIB_SENSOR_AEC_FPS_FPS_FIX_TIMEDOT_TAG_ID,
	//aec interval adjust
	CALIB_SENSOR_AEC_INTERVAL_ADJUST_STRATEGY_TAG_ID,
	CALIB_SENSOR_AEC_INTERVAL_ADJUST_ENABLE_TAG_ID,
	CALIB_SENSOR_AEC_INTERVAL_ADJUST_DLUMA_HIGH_TH_TAG_ID,
	CALIB_SENSOR_AEC_INTERVAL_ADJUST_DLUMA_LOW_TH_TAG_ID,
	CALIB_SENSOR_AEC_INTERVAL_ADJUST_TRIGGER_FRAME_TAG_ID,
	//aec AOE
	CALIB_SENSOR_AEC_AOE_ENABLE_TAG_ID,
	CALIB_SENSOR_AEC_AOE_MAX_POINT_TAG_ID,
	CALIB_SENSOR_AEC_AOE_MIN_POINT_TAG_ID,
	CALIB_SENSOR_AEC_AOE_Y_MAX_TH_TAG_ID,
	CALIB_SENSOR_AEC_AOE_Y_MIN_TH_TAG_ID,
	CALIB_SENSOR_AEC_AOE_STEP_INC_TAG_ID,
	CALIB_SENSOR_AEC_AOE_STEP_DEC_TAG_ID,
	/* Day or Night */
	CALIB_SENSOR_AEC_DON_TAG_ID,
	CALIB_SENSOR_AEC_DON_NIGHT_TRIGGER_TAG_ID,
	CALIB_SENSOR_AEC_DON_NIGHT_MODE_TAG_ID,
	CALIB_SENSOR_AEC_DON_DAY2NIGHT_FAC_TH_TAG_ID,
	CALIB_SENSOR_AEC_DON_NIGHT2DAY_FAC_TH_TAG_ID,
	CALIB_SENSOR_AEC_DON_BOUNCING_TH_TAG_ID,
	//NLSC
	CALIB_SENSOR_AEC_NLSC_CONFIG_TAG_ID,
	CALIB_SENSOR_AEC_NLSC_ENABLE_TAG_ID,
	CALIB_SENSOR_AEC_NLSC_IR_RG_TAG_ID,
	CALIB_SENSOR_AEC_NLSC_IR_BG_TAG_ID,
	CALIB_SENSOR_AEC_NLSC_MAX_DIS_TAG_ID,
	CALIB_SENSOR_AEC_NLSC_COLOR2BLACK_COUNT_TAG_ID,
	CALIB_SENSOR_AEC_NLSC_COLOR2BLACK_THRESH_TAG_ID,
	CALIB_SENSOR_AEC_NLSC_BLACK2COLOR_COUNT_TAG_ID,
	CALIB_SENSOR_AEC_NLSC_BLACK2COLOR_THRESH_TAG_ID,
	CALIB_SENSOR_AEC_NLSC_BLACK2COLOR_VB_PERCENT_TAG_ID,
	CALIB_SENSOR_AEC_NLSC_COLOR2BLACK_STABLE_FPS_TAG_ID,
	//backlight
	CALIB_SENSOR_AEC_BACKLIGHT_CONFIG_TAG_ID,
	CALIB_SENSOR_AEC_BACKLIGHT_ENABLE_TAG_ID,
	CALIB_SENSOR_AEC_BACKLIGHT_LUMALOWTH_TAG_ID,
	CALIB_SENSOR_AEC_BACKLIGHT_LUMAHIGHTH_TAG_ID,
	CALIB_SENSOR_AEC_BACKLIGHT_WEIGHTMINTH_TAG_ID,
	CALIB_SENSOR_AEC_BACKLIGHT_WEIGHTMAXTH_TAG_ID,
	//hist 2 hal
	CALIB_SENSOR_AEC_HIST_2_HAL_TAG_ID,
	CALIB_SENSOR_AEC_HIST_2_HAL_ENABLE_TAG_ID,
	CALIB_SENSOR_AEC_HIST_2_HAL_LOWHISTBINTH_TAG_ID,
	/*LockAE-for HDR*/
	CALIB_SENSOR_LOCK_AE_TAG_ID,
	CALIB_SENSOR_LOCK_AE_ENABEL_TAG_ID,
	CALIB_SENSOR_LOCK_AE_GAINVALUE_TAG_ID,
	CALIB_SENSOR_LOCK_AE_TIMEVALUE_TAG_ID,
	//CALIB_SENSOR_LOCK_AE_MEANLUMADISTTH_TAG_ID,     ???
	/*HDR-Ctrl*/
	CALIB_SENSOR_HDRCTRL_TAG_ID,
	CALIB_SENSOR_HDRCTRL_ENABEL_TAG_ID,
	CALIB_SENSOR_HDRCTRL_MODE_TAG_ID,
	CALIB_SENSOR_HDRCTRL_FRAMENUM_TAG_ID,
	CALIB_SENSOR_HDRCTRL_DCG_Ratio_TAG_ID,
	CALIB_SENSOR_HDRCTRL_M2S_Ratio_TAG_ID,
	CALIB_SENSOR_HDRCTRL_L2M_Ratio_TAG_ID,
	//Lframe ctrl
	CALIB_SENSOR_HDRCTRL_LFRAMECTRL_TAG_ID,
	CALIB_SENSOR_HDRCTRL_LGAINS_TAG_ID,
	CALIB_SENSOR_HDRCTRL_LEXPLEVEL_TAG_ID,
	CALIB_SENSOR_HDRCTRL_LSETPOINT_TAG_ID,
	CALIB_SENSOR_HDRCTRL_DARKLUMA_TAG_ID,
	//sframe ctrl
	CALIB_SENSOR_HDRCTRL_SFRAMECTRL_TAG_ID,
	CALIB_SENSOR_HDRCTRL_SGAINS_TAG_ID,
	CALIB_SENSOR_HDRCTRL_SEXPLEVEL_TAG_ID,
	CALIB_SENSOR_HDRCTRL_OETOLERANCE_TAG_ID,
	CALIB_SENSOR_HDRCTRL_OELUMA_TAG_ID,
	CALIB_SENSOR_HDRCTRL_SSETPOINT_TAG_ID,
	CALIB_SENSOR_HDRCTRL_OELUMADIST_TAG_ID,


	/******************************************************************************
	 * XML BLS section
	 *****************************************************************************/
	CALIB_SENSOR_BLS_TAG_ID,
	CALIB_SENSOR_BLS_NAME_TAG_ID,
	CALIB_SENSOR_BLS_RESOLUTION_TAG_ID,
	CALIB_SENSOR_BLS_DATA_TAG_ID,


	/******************************************************************************
	 * XML DEGAMMA section
	 *****************************************************************************/
	CALIB_SENSOR_DEGAMMA_TAG_ID,

	/******************************************************************************
	 * XML GOC section
	 *****************************************************************************/
	CALIB_SENSOR_GOC_TAG_ID,
	CALIB_SENSOR_GOC_NAME_TAG_ID,
	CALIB_SENSOR_GOC_ENABLE_MODE_TAG_ID,
	CALIB_SENSOR_GOC_DEF_CFG_MODE_TAG_ID,
	CALIB_SENSOR_GOC_GAMMAY_TAG_ID,
	CALIB_SENSOR_GOC_WDRON_GAMMAY_TAG_ID,


	/******************************************************************************
	 * XML WDR section
	 *****************************************************************************/
	CALIB_SENSOR_WDR_TAG_ID,
	CALIB_SENSOR_WDR_ENABLE_TAG_ID,
	CALIB_SENSOR_WDR_MODE_TAG_ID,

	CALIB_SENSOR_WDR_TBD_TAG_ID,
	CALIB_SENSOR_WDR_CURVE1_TAG_ID,
	CALIB_SENSOR_WDR_CURVE2_TAG_ID,

	CALIB_SENSOR_WDR_LOCAL_CURVE_TAG_ID,
	CALIB_SENSOR_WDR_GLOBAL_CURVE_TAG_ID,
	CALIB_SENSOR_WDR_NOISE_RATIO_TAG_ID,
	CALIB_SENSOR_WDR_BEST_LIGHT_TAG_ID,
	CALIB_SENSOR_WDR_GAIN_OFF1_TAG_ID,
	CALIB_SENSOR_WDR_PYM_TAG_ID,
	CALIB_SENSOR_WDR_EPSILON_TAG_ID,
	CALIB_SENSOR_WDR_LVL_TAG_ID,
	CALIB_SENSOR_WDR_FLT_TAG_ID,
	CALIB_SENSOR_WDR_GAIN_MAX_CLIP_ENABLE_TAG_ID,
	CALIB_SENSOR_WDR_GAIN_MAX_VALUE_TAG_ID,
	CALIB_SENSOR_WDR_BAVG_TAG_ID,
	CALIB_SENSOR_WDR_NONL_SEGM_TAG_ID,
	CALIB_SENSOR_WDR_NONL_OPEN_TAG_ID,
	CALIB_SENSOR_WDR_NONL_MODE1_TAG_ID,
	CALIB_SENSOR_WDR_COE0_TAG_ID,
	CALIB_SENSOR_WDR_COE1_TAG_ID,
	CALIB_SENSOR_WDR_COE2_TAG_ID,
	CALIB_SENSOR_WDR_COE_OFF_TAG_ID,

	CALIB_SENSOR_WDR_MAXGAIN_FILTER_TAG_ID,
	CALIB_SENSOR_WDR_MAXGAIN_FILTER_ENABLE_TAG_ID,
	CALIB_SENSOR_WDR_MAXGAIN_SENSOR_GAIN_LEVEL_TAG_ID,
	CALIB_SENSOR_WDR_MAXGAIN_MAXGAIN_LEVEL_TAG_ID,


	/******************************************************************************
	 * XML CAC section
	 *****************************************************************************/
	CALIB_SENSOR_CAC_TAG_ID,
	CALIB_SENSOR_CAC_NAME_TAG_ID,
	CALIB_SENSOR_CAC_RESOLUTION_TAG_ID,
	CALIB_SESNOR_CAC_X_NORMSHIFT_TAG_ID,
	CALIB_SESNOR_CAC_X_NORMFACTOR_TAG_ID,
	CALIB_SESNOR_CAC_Y_NORMSHIFT_TAG_ID,
	CALIB_SESNOR_CAC_Y_NORMFACTOR_TAG_ID,
	CALIB_SESNOR_CAC_X_OFFSET_TAG_ID,
	CALIB_SESNOR_CAC_Y_OFFSET_TAG_ID,
	CALIB_SESNOR_CAC_RED_PARAMETERS_TAG_ID,
	CALIB_SESNOR_CAC_BLUE_PARAMETERS_TAG_ID,


	/******************************************************************************
	 * XML DPF section
	 *************************************************************************/
	CALIB_SENSOR_DPF_TAG_ID,
	CALIB_SENSOR_DPF_NAME_TAG_ID,
	CALIB_SENSOR_DPF_RESOLUTION_TAG_ID,
	CALIB_SENSOR_DPF_ADPF_ENABLE_TAG_ID,
	CALIB_SENSOR_DPF_NLL_SEGMENTATION_TAG_ID,
	CALIB_SENSOR_DPF_NLL_COEFF_TAG_ID,
	CALIB_SENSOR_DPF_SIGMA_GREEN_TAG_ID,
	CALIB_SENSOR_DPF_SIGMA_RED_BLUE_TAG_ID,
	CALIB_SENSOR_DPF_GRADIENT_TAG_ID,
	CALIB_SENSOR_DPF_OFFSET_TAG_ID,
	CALIB_SENSOR_DPF_NLGAINS_TAG_ID,

	CALIB_SENSOR_DPF_FILTERSETTING_TAG_ID,
	CALIB_SENSOR_DPF_FILTERSETTING_NAME_TAG_ID,
	CALIB_SENSOR_DPF_FILTERENABLE_TAG_ID,
	CALIB_SENSOR_DPF_DENOISELEVEL_TAG_ID,
	CALIB_SENSOR_DPF_DENOISELEVEL_GAINS_TAG_ID,
	CALIB_SENSOR_DPF_DENOISELEVEL_DLEVEL_TAG_ID,
	CALIB_SENSOR_DPF_SHARPENINGLEVEL_TAG_ID,
	CALIB_SENSOR_DPF_SHARPENINGLEVEL_GAINS_TAG_ID,
	CALIB_SENSOR_DPF_SHARPENINGLEVEL_SLEVEL_TAG_ID,

	CALIB_SENSOR_DPF_FILT_LEVEL_REG_CONF_TAG_ID,
	CALIB_SENSOR_DPF_FILT_LEVEL_REG_CONF_ENABLE_TAG_ID,
	CALIB_SENSOR_DPF_FILT_LEVEL_TAG_ID,
	CALIB_SENSOR_DPF_FILT_CHR_H_MODE_TAG_ID,
	CALIB_SENSOR_DPF_FILT_CHR_V_MODE_TAG_ID,
	CALIB_SENSOR_DPF_FILT_GRN_STAGE1_TAG_ID,
	CALIB_SENSOR_DPF_FILT_THRESH_BL0_TAG_ID,
	CALIB_SENSOR_DPF_FILT_THRESH_BL1_TAG_ID,
	CALIB_SENSOR_DPF_FILT_FAC_BL0_TAG_ID,
	CALIB_SENSOR_DPF_FILT_FAC_BL1_TAG_ID,
	CALIB_SENSOR_DPF_FILT_THRESH_SH0_TAG_ID,
	CALIB_SENSOR_DPF_FILT_THRESH_SH1_TAG_ID,
	CALIB_SENSOR_DPF_FILT_FAC_SH0_TAG_ID,
	CALIB_SENSOR_DPF_FILT_FAC_SH1_TAG_ID,
	CALIB_SENSOR_DPF_FILT_FAC_MID_TAG_ID,

	CALIB_SENSOR_DPF_FILT_DEMOSAIC_TH_CONF_TAG_ID,
	CALIB_SENSOR_DPF_FILT_DEMOSAIC_TH_GAIN_TAG_ID,
	CALIB_SENSOR_DPF_FILT_DEMOSAIC_TH_LEVEL_TAG_ID,

	//demosaic lp
	CALIB_SENSOR_DPF_DEMOSAIC_LP_CONF_TAG_ID,
	CALIB_SENSOR_DPF_LP_EN_TAG_ID,
	CALIB_SENSOR_DPF_LP_USE_OLD_VERSION_TAG_ID,
	CALIB_SENSOR_DPF_LP_LU_DIVIDED_TAG_ID,
	CALIB_SENSOR_DPF_LP_GAINSARRAY_TAG_ID,
	CALIB_SENSOR_DPF_LP_THH_DIVIDED0_TAG_ID,
	CALIB_SENSOR_DPF_LP_THH_DIVIDED1_TAG_ID,
	CALIB_SENSOR_DPF_LP_THH_DIVIDED2_TAG_ID,
	CALIB_SENSOR_DPF_LP_THH_DIVIDED3_TAG_ID,
	CALIB_SENSOR_DPF_LP_THH_DIVIDED4_TAG_ID,
	CALIB_SENSOR_DPF_LP_THCSC_DIVIDED0_TAG_ID,
	CALIB_SENSOR_DPF_LP_THCSC_DIVIDED1_TAG_ID,
	CALIB_SENSOR_DPF_LP_THCSC_DIVIDED2_TAG_ID,
	CALIB_SENSOR_DPF_LP_THCSC_DIVIDED3_TAG_ID,
	CALIB_SENSOR_DPF_LP_THCSC_DIVIDED4_TAG_ID,
	CALIB_SENSOR_DPF_LP_DIFF_DIVIDED0_TAG_ID,
	CALIB_SENSOR_DPF_LP_DIFF_DIVIDED1_TAG_ID,
	CALIB_SENSOR_DPF_LP_DIFF_DIVIDED2_TAG_ID,
	CALIB_SENSOR_DPF_LP_DIFF_DIVIDED3_TAG_ID,
	CALIB_SENSOR_DPF_LP_DIFF_DIVIDED4_TAG_ID,
	CALIB_SENSOR_DPF_LP_VARTH_DIVIDED0_TAG_ID,
	CALIB_SENSOR_DPF_LP_VARTH_DIVIDED1_TAG_ID,
	CALIB_SENSOR_DPF_LP_VARTH_DIVIDED2_TAG_ID,
	CALIB_SENSOR_DPF_LP_VARTH_DIVIDED3_TAG_ID,
	CALIB_SENSOR_DPF_LP_VARTH_DIVIDED4_TAG_ID,
	CALIB_SENSOR_DPF_LP_THGRAD_R_FCT_TAG_ID,
	CALIB_SENSOR_DPF_LP_THDIFF_R_FCT_TAG_ID,
	CALIB_SENSOR_DPF_LP_THVAR_R_FCT_TAG_ID,
	CALIB_SENSOR_DPF_LP_THGRAD_B_FCT_TAG_ID,
	CALIB_SENSOR_DPF_LP_THDIFF_B_FCT_TAG_ID,
	CALIB_SENSOR_DPF_LP_THVAR_B_FCT_TAG_ID,
	CALIB_SENSOR_DPF_LP_SIMILARITY_TH_TAG_ID,
	CALIB_SENSOR_DPF_LP_TH_VAR_EN_TAG_ID,
	CALIB_SENSOR_DPF_LP_TH_CSC_EN_TAG_ID,
	CALIB_SENSOR_DPF_LP_TH_DIFF_EN_TAG_ID,
	CALIB_SENSOR_DPF_LP_TH_GRAD_EN_TAG_ID,
	CALIB_SENSOR_DPF_LP_TH_GRAD_TAG_ID,
	CALIB_SENSOR_DPF_LP_TH_VAR_TAG_ID,
	CALIB_SENSOR_DPF_LP_TH_DIFF_TAG_ID,
	CALIB_SENSOR_DPF_LP_TH_CSC_TAG_ID,
	CALIB_SENSOR_DPF_LP_FLAT_LEVEL_SEL_TAG_ID,
	CALIB_SENSOR_DPF_LP_PATTERN_LEVEL_SEL_TAG_ID,
	CALIB_SENSOR_DPF_LP_EDGE_LEVEL_SEL_TAG_ID,
	CALIB_SENSOR_DPF_LP_RB_FILTER_EN_TAG_ID,
	CALIB_SENSOR_DPF_LP_HP_FILTER_EN_TAG_ID,

	//mfd
	CALIB_SESNOR_MFD_ENABLE_TAG_ID,
	CALIB_SESNOR_MFD_GAIN_TAG_ID,
	CALIB_SESNOR_MFD_FRAMES_TAG_ID,

	//uvnr
	CALIB_SESNOR_UVNR_ENABLE_TAG_ID,
	CALIB_SESNOR_UVNR_GAIN_TAG_ID,
	CALIB_SESNOR_UVNR_RATIO_TAG_ID,
	CALIB_SESNOR_UVNR_DISTANCE_TAG_ID,

	// 3ndr by jiang ming jun
	CALIB_SENSOR_DSP_3DNR_SETTING_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_NAME_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_ENABLE_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_GAIN_LEVEL_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_NOISE_COEF_NUMERATOR_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_NOISE_COEF_DENOMINATOR_TAG_ID,

	//3dnr level setting
	CALIB_SENSOR_DSP_3DNR_SETTING_LEVEL_SETTING_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_SP_NR_EN_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_SP_NR_LEVEL_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_TE_NR_EN_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_TE_NR_LEVEL_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_SP_NR_EN_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_SP_NR_LEVEL_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_TE_NR_EN_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_TE_NR_LEVEL_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SHP_EN_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SHP_LEVEL_TAG_ID,

	//3dnr luma setting
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_SETTING_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_DEFAULT_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_SP_RAD_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_TE_MAX_BI_NUM_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W00_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W01_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W02_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W03_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W04_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W10_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W11_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W12_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W13_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W14_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W20_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W21_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W22_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W23_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W24_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W30_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W31_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W32_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W33_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W34_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W40_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W41_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W42_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W43_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_LUMA_W44_TAG_ID,

	//3dnr chrm setting
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_SETTING_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_DEFAULT_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_SP_RAD_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_TE_MAX_BI_NUM_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W00_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W01_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W02_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W03_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W04_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W10_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W11_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W12_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W13_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W14_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W20_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W21_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W22_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W23_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W24_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W30_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W31_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W32_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W33_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W34_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W40_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W41_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W42_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W43_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_CHRM_W44_TAG_ID,

	//3dnr sharp settint
	CALIB_SENSOR_DSP_3DNR_SETTING_SHP_SETTING_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SHP_DEFAULT_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_THR_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_DIV_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_L_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_C_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W00_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W01_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W02_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W03_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W04_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W10_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W11_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W12_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W13_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W14_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W20_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W21_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W22_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W23_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W24_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W30_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W31_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W32_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W33_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W34_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W40_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W41_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W42_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W43_TAG_ID,
	CALIB_SENSOR_DSP_3DNR_SETTING_SRC_SHP_W44_TAG_ID,

	// new 3dnr by luo ning
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_NAME_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_3DNR_ENABLE_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_DPC_ENABLE_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_GAIN_LEVEL_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_YNR_SETTING_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_YNR_ENABLE_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_TNR_ENABLE_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_IIR_ENABLE_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_YNR_TIME_LEVEL_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_YNR_SPACE_LEVEL_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_UVNR_SETTING_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_UVNR_ENABLE_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_UVNR_LEVEL_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_SHARP_SETTING_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_SHARP_ENABLE_TAG_ID,
	CALIB_SENSOR_NEW_DSP_3DNR_SETTING_SHARP_LEVEL_TAG_ID,


	/******************************************************************************
	 * XML DPCC section
	 *****************************************************************************/
	CALIB_SENSOR_DPCC_TAG_ID,
	CALIB_SENSOR_DPCC_NAME_TAG_ID,
	CALIB_SENSOR_DPCC_RESOLUTION_TAG_ID,
	CALIB_SENSOR_DPCC_REGISTER_TAG_ID,
	CALIB_SENSOR_DPCC_REGISTER_NAME_TAG_ID,
	CALIB_SENSOR_DPCC_REGISTER_VALUE_TAG_ID,

	/******************************************************************************
	 * XML IESHARPEN section
	 *****************************************************************************/
	CALIB_SENSOR_IESHARPEN_TAG_ID,
	CALIB_SENSOR_IESHARPEN_NAME_TAG_ID,
	CALIB_SENSOR_IESHARPEN_RESOLUTION_TAG_ID,
	CALIB_SENSOR_IESHARPEN_ENABLE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_CORING_THR_TAG_ID,
	CALIB_SENSOR_IESHARPEN_FULL_RANGE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_SWITCH_AVG_TAG_ID,
	CALIB_SENSOR_IESHARPEN_YAVG_THR_TAG_ID,
	CALIB_SENSOR_IESHARPEN_P_DELTA1_TAG_ID,
	CALIB_SENSOR_IESHARPEN_P_DELTA2_TAG_ID,
	CALIB_SENSOR_IESHARPEN_P_MAX_NUMBER_TAG_ID,
	CALIB_SENSOR_IESHARPEN_P_MIN_NUMBER_TAG_ID,
	CALIB_SENSOR_IESHARPEN_GAUSS_FLAT_COE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_GAUSS_NOISE_COE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_GAUSS_OTHER_COE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_L_P_GRAD_TAG_ID,
	CALIB_SENSOR_IESHARPEN_L_SHARP_FACTOR_TAG_ID,
	CALIB_SENSOR_IESHARPEN_L_LINE1_FILTER_COE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_L_LINE2_FILTER_COE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_L_LINE3_FILTER_COE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_H_P_GRAD_TAG_ID,
	CALIB_SENSOR_IESHARPEN_H_SHARP_FACTOR_TAG_ID,
	CALIB_SENSOR_IESHARPEN_H_LINE1_FILTER_COE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_H_LINE2_FILTER_COE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_H_LINE3_FILTER_COE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_UV_GAUSS_FLAT_COE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_UV_GAUSS_NOISE_COE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_UV_GAUSS_OTHER_COE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_GAIN_DVIDE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_L_LAP_MAT_COE_TAG_ID,
	CALIB_SENSOR_IESHARPEN_H_LAP_MAT_COE_TAG_ID,



	/******************************************************************************
	 * XML CPROC section
	 *****************************************************************************/
	CALIB_SENSOR_CPROC_TAG_ID,
	CALIB_SENSOR_CPROC_NAME_TAG_ID,
	CALIB_SENSOR_CPROC_SATURATION_TAG_ID,
	CALIB_SENSOR_CPROC_CONTRAST_TAG_ID,
	CALIB_SENSOR_CPROC_BRIGHTNESS_TAG_ID,
	CALIB_SENSOR_CPROC_HUE_TAG_ID,

	/******************************************************************************
	 * XML OTP INFO section
	 *****************************************************************************/
	CALIB_SENSOR_OTP_TAG_ID,
	CALIB_SENSOR_OTP_AWB_ENABLE_TAG_ID,
	CALIB_SENSOR_OTP_AWB_GOLDEN_R_VALUE_TAG_ID,
	CALIB_SENSOR_OTP_AWB_GOLDEN_GR_VALUE_TAG_ID,
	CALIB_SENSOR_OTP_AWB_GOLDEN_GB_VALUE_TAG_ID,
	CALIB_SENSOR_OTP_AWB_GOLDEN_B_VALUE_TAG_ID,
	CALIB_SENSOR_OTP_LSC_ENABLE_TAG_ID,

	/******************************************************************************
	 * XML system section
	 *****************************************************************************/
	CALIB_SYSTEM_TAG_ID,
	CALIB_SYSTEM_AFPS_TAG_ID,
	CALIB_SYSTEM_AFPS_DEFAULT_TAG_ID,
	CALIB_IQ_TAG_END,
} CALIB_IQ_TAG_ID_T;

typedef enum CALIB_TAG_TYPE_E {
    CALIB_TAG_TYPE_UNKNOWN = 0,
    CALIB_TAG_TYPE_CHAR,
    CALIB_TAG_TYPE_DOUBLE,
    CALIB_TAG_TYPE_STRUCT,
    CALIB_TAG_TYPE_CELL,
} CALIB_TAG_TYPE_T;

typedef int16_t calib_tag_2d_array[2];

typedef struct calib_tag_info_s {
    const char* name;
    const CALIB_TAG_TYPE_T type;
    // two dimensions
    // and value always be {1, n} for one dimension case
    // if the size is unknown or dynamic, set the value to -1
    const calib_tag_2d_array size;
    const uint32_t* sub_tags_array;
    const int32_t sub_tags_array_size;
    // dynamic allocated
    void* check_info;
} calib_tag_info_t;

extern calib_tag_info_t g_calib_tag_infos[CALIB_IQ_TAG_END];

#define TAG_NAME(id) (g_calib_tag_infos[id].name)
#define TAG_TYPE(id) (XmlTag::TagType_e)(g_calib_tag_infos[id].type)
#define TAG_SIZE(id) (g_calib_tag_infos[id].size[0] * g_calib_tag_infos[id].size[1])

uint32_t calib_check_calc_checksum();

int calib_check_getID_by_name(char* tag_name, 
									CALIB_IQ_TAG_ID_T parent_tag_id, 
									CALIB_IQ_TAG_ID_T *tag_id );

int calib_check_cell_set_size(CALIB_IQ_TAG_ID_T tag_id, 
									CALIB_IQ_TAG_ID_T parent_tag_id, 
									int size);

int calib_check_tag_attrs(CALIB_IQ_TAG_ID_T tag_id,
                          uint32_t type,
                          int size,
                          CALIB_IQ_TAG_ID_T parent_tag_id);

int calib_check_nonleaf_tag_start(CALIB_IQ_TAG_ID_T tag_id, 
										CALIB_IQ_TAG_ID_T parent_tag_id);
int calib_check_tag_mark(CALIB_IQ_TAG_ID_T tag_id,
                         CALIB_IQ_TAG_ID_T parent_tag_id);
int calib_check_nonleaf_tag_end(CALIB_IQ_TAG_ID_T tag_id);

#endif /* __CALIB_TAGS_H__ */

