include(CMakeDependentOption)

cmake_dependent_option(RKAIQ_BUILD_DOCS "Build all of rkaiq's documents." OFF "WIN32" OFF)
cmake_dependent_option(RKAIQ_BUILD_TESTS "Build all of rkaiq's own tests." OFF "WIN32" OFF)
cmake_dependent_option(RKAIQ_BUILD_EXAMPLES "Build all of rkaiq's own examples." OFF "WIN32" OFF)
cmake_dependent_option(RKAIQ_ENABLE_ASAN "Build libraries/executable with address santilizer" OFF "WIN32" OFF)
cmake_dependent_option(RKAIQ_ENABLE_SIMULATOR "Build simulator for algos run on PC" OFF "WIN32" OFF)
set(RKAIQ_ENABLE_PARSER_V1   FALSE CACHE INTERNAL "Build rkaiq's old xml parser")
set(RKAIQ_ENABLE_CAMGROUP    FALSE CACHE INTERNAL "Build rkaiq's camera group algorithms")
set(RKAIQ_ENABLE_LIBDRM      TRUE  CACHE INTERNAL "Build rkaiq with libdrm")
set(RKAIQ_HAVE_FAKECAM       FALSE CACHE INTERNAL "Build rkaiq's Fake Cam")
set(RKAIQ_HAVE_SPSTREAM      FALSE CACHE INTERNAL "Build rkaiq's SP Stream")
set(RKAIQ_HAVE_THUMBNAILS    FALSE CACHE INTERNAL "Build rkaiq's Thumbnails Service")
set(RKAIQ_HAVE_MULTIISP      FALSE CACHE INTERNAL "Build rkaiq's Dual ISP")
set(RKAIQ_ENABLE_AF          FALSE CACHE INTERNAL "Build rkaiq's AF algorithm")
set(RKAIQ_HAVE_ONLY_CUSTOM_AF FALSE CACHE INTERNAL "Build AF stats for custom algorithm")
set(RKAIQ_INSTALL_ALGOS_LIB FALSE CACHE INTERNAL "Install algos lib to algos dir")
set(RKAIQ_USE_RAWSTREAM_LIB FALSE CACHE INTERNAL "Build rkaiq with libstream")
set(RKAIQ_J2S4B_DEV          TRUE CACHE INTERNAL "Build j2s4b_dev running on device")
set(RKAIQ_NEWSTRUCT_TEST     FALSE CACHE INTERNAL "Build rkaiq with new structs")

if (RKAIQ_TARGET_SOC STREQUAL "rk3576")
    set(RKAIQ_ISP_VERSION        "39"  CACHE INTERNAL "ISP hardware version 39"     FORCE)
elseif (RKAIQ_TARGET_SOC STREQUAL "rk3562")
    set(RKAIQ_ISP_VERSION        "32_lite"  CACHE INTERNAL "ISP hardware version 32 lite"     FORCE)
elseif (RKAIQ_TARGET_SOC STREQUAL "rv1106")
    # set(RKAIQ_NEWSTRUCT_TEST     TRUE)
    set(RKAIQ_ISP_VERSION        "32"  CACHE INTERNAL "ISP hardware version 32"               FORCE)
elseif (RKAIQ_TARGET_SOC STREQUAL "rk3588")
    set(RKAIQ_ISP_VERSION        "30"  CACHE INTERNAL "ISP hardware version 30"               FORCE)
    set(RKAIQ_ENABLE_CAMGROUP    TRUE  CACHE INTERNAL "Build rkaiq's camera group algorithms" FORCE)
    set(RKAIQ_HAVE_THUMBNAILS    TRUE  CACHE INTERNAL "Build rkaiq's Thumbnails Service"      FORCE)
    set(RKAIQ_HAVE_MULTIISP      TRUE  CACHE INTERNAL "Build rkaiq's Dual ISP"                FORCE)
elseif (RKAIQ_TARGET_SOC STREQUAL "rk356x")
    set(RKAIQ_ISP_VERSION        "21"  CACHE INTERNAL "ISP hardware version 21"               FORCE)
elseif (RKAIQ_TARGET_SOC STREQUAL "rv1109")
    set(RKAIQ_ISP_VERSION        "20"  CACHE INTERNAL "ISP hardware version 20"               FORCE)
else()
    set(RKAIQ_ISP_VERSION        "30"  CACHE INTERNAL "No ISP hardware version specificed"    FORCE)
    message(WARNING "RKAIQ_TARGET_SOC SHOULD be set")
endif()

message(STATUS "Building ISP v${RKAIQ_ISP_VERSION} rkaiq for soc ${RKAIQ_TARGET_SOC}")

if (ISP_HW_VERSION STRLESS "-DISP_HW_V20")
    message(FATAL_ERROR "ISP_HW_VERSION MUST be set")
endif()

set(RKAIQ_HAVE_AWB  TRUE CACHE INTERNAL "Build rkaiq's AWB"      FORCE)
set(RKAIQ_HAVE_GIC  TRUE CACHE INTERNAL "Build rkaiq's GIC"       FORCE)
set(RKAIQ_HAVE_CAC  TRUE  CACHE INTERNAL "Build rkaiq's CAC"      FORCE)
set(RKAIQ_HAVE_YNR  TRUE  CACHE INTERNAL "Build rkaiq's YNR"      FORCE)
set(RKAIQ_HAVE_CNR   TRUE CACHE INTERNAL "Build rkaiq's CNR"       FORCE)
set(RKAIQ_HAVE_SHARP TRUE CACHE INTERNAL "Build rkaiq's SHARP"     FORCE)
set(RKAIQ_HAVE_BAYERNR  TRUE CACHE INTERNAL "Build rkaiq's BAYERNR"      FORCE)
set(RKAIQ_HAVE_BAYER2DNR TRUE  CACHE INTERNAL "Build rkaiq's BAYER2DNR"  FORCE)
set(RKAIQ_HAVE_BAYERTNR  TRUE CACHE INTERNAL "Build rkaiq's BAYERTNR"   FORCE)
set(RKAIQ_HAVE_GAIN  TRUE  CACHE INTERNAL "Build rkaiq's GAIN"      FORCE)
set(RKAIQ_HAVE_BLC   TRUE  CACHE INTERNAL "Build rkaiq's BLC"      FORCE)
set(RKAIQ_HAVE_AF   TRUE CACHE INTERNAL "Build rkaiq's AF"       FORCE)
set(RKAIQ_HAVE_3DLUT TRUE  CACHE INTERNAL "Build rkaiq's 3DLUT"       FORCE)
set(RKAIQ_HAVE_CCM   TRUE  CACHE INTERNAL "Build rkaiq's CCM"       FORCE)
set(RKAIQ_HAVE_GAMMA   TRUE CACHE INTERNAL "Build rkaiq's GAMMA"       FORCE)
set(RKAIQ_HAVE_MERGE   TRUE CACHE INTERNAL "Build rkaiq's MERGE"       FORCE)
set(RKAIQ_HAVE_DRC   TRUE CACHE INTERNAL "Build rkaiq's DRC"       FORCE)
set(RKAIQ_HAVE_DEHAZE   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE"       FORCE)
set(RKAIQ_HAVE_WDR   TRUE CACHE INTERNAL "Build rkaiq's WDR"       FORCE)
set(RKAIQ_HAVE_LDCH  TRUE  CACHE INTERNAL "Build rkaiq's LDCH"    FORCE)
set(RKAIQ_HAVE_CSM   TRUE CACHE INTERNAL "Build rkaiq's CSM"       FORCE)
set(RKAIQ_HAVE_CGC   TRUE CACHE INTERNAL "Build rkaiq's CGC"       FORCE)
set(RKAIQ_HAVE_AE   TRUE CACHE INTERNAL "Build rkaiq's AE"       FORCE)
set(RKAIQ_HAVE_AFD   TRUE CACHE INTERNAL "Build rkaiq's AFD"       FORCE)
set(RKAIQ_HAVE_DEBAYER   TRUE CACHE INTERNAL "Build rkaiq's DEBAYER"       FORCE)
set(RKAIQ_HAVE_LSC   TRUE CACHE INTERNAL "Build rkaiq's LSC"       FORCE)
set(RKAIQ_HAVE_DPCC   TRUE CACHE INTERNAL "Build rkaiq's DPCC"       FORCE)
set(RKAIQ_HAVE_ACP   TRUE CACHE INTERNAL "Build rkaiq's ACP"       FORCE)
set(RKAIQ_HAVE_AIE   TRUE CACHE INTERNAL "Build rkaiq's AIE"       FORCE)
set(RKAIQ_HAVE_ASD  FALSE CACHE INTERNAL "Build rkaiq's ASD"       FORCE)
set(RKAIQ_HAVE_ORB   FALSE CACHE INTERNAL "Build rkaiq's ORB"       FORCE)
set(RKAIQ_HAVE_EIS   FALSE CACHE INTERNAL "Build rkaiq's EIS"       FORCE)
set(RKAIQ_HAVE_UVNR FALSE CACHE INTERNAL "Build rkaiq's UVNR"      FORCE)
set(RKAIQ_HAVE_MFNR  FALSE CACHE INTERNAL "Build rkaiq's MFNR"      FORCE)
set(RKAIQ_HAVE_ANR   FALSE CACHE INTERNAL "Build rkaiq's ANR"      FORCE)
set(RKAIQ_HAVE_AMD   FALSE CACHE INTERNAL "Build rkaiq's AMD"      FORCE)
set(RKAIQ_HAVE_TMO   FALSE CACHE INTERNAL "Build rkaiq's TMO"       FORCE)
set(RKAIQ_HAVE_FEC  FALSE CACHE INTERNAL "Build rkaiq's FEC"    FORCE)

set(RKAIQ_HAVE_YUVME  FALSE  CACHE INTERNAL "Build rkaiq's YUVME"      FORCE)
set(RKAIQ_HAVE_RGBIR_REMOSAIC   FALSE CACHE INTERNAL "Build rkaiq's RGBIR remosaic"       FORCE)
if (RKAIQ_ISP_VERSION STREQUAL "39")
    set(RKAIQ_HAVE_BAYERNR  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR"  FORCE)
    set(RKAIQ_HAVE_YUVME  TRUE  CACHE INTERNAL "Build rkaiq's YUVME"      FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "32_lite")
    set(RKAIQ_HAVE_GIC  FALSE CACHE INTERNAL "Build rkaiq's GIC"       FORCE)
    set(RKAIQ_HAVE_CAC FALSE  CACHE INTERNAL "Build rkaiq's CAC"      FORCE)
    set(RKAIQ_HAVE_BAYERNR  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR FALSE  CACHE INTERNAL "Build rkaiq's BAYER2DNR"  FORCE)
    set(RKAIQ_HAVE_AFD  FALSE CACHE INTERNAL "Build rkaiq's AFD"       FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "32")
    set(RKAIQ_HAVE_BAYERNR  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR"      FORCE)
    if (NOT RKAIQ_ENABLE_AF)
        set(RKAIQ_HAVE_AF   FALSE CACHE INTERNAL "Build rkaiq's AF"       FORCE)
    endif()
elseif (RKAIQ_ISP_VERSION STREQUAL "30")
    set(RKAIQ_HAVE_BAYERNR  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR"      FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "21")
    set(RKAIQ_HAVE_CAC  FALSE CACHE INTERNAL "Build rkaiq's CAC"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR"   FORCE)
    set(RKAIQ_HAVE_GAIN  FALSE CACHE INTERNAL "Build rkaiq's GAIN"      FORCE)
    set(RKAIQ_HAVE_AFD   FALSE CACHE INTERNAL "Build rkaiq's AFD"       FORCE)
    set(RKAIQ_HAVE_DEGAMMA   TRUE CACHE INTERNAL "Build rkaiq's DEGAMMA"       FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "20")
    set(RKAIQ_HAVE_CAC  FALSE CACHE INTERNAL "Build rkaiq's CAC"      FORCE)
    set(RKAIQ_HAVE_YNR   FALSE CACHE INTERNAL "Build rkaiq's YNR"       FORCE)
    set(RKAIQ_HAVE_CNR  FALSE CACHE INTERNAL "Build rkaiq's CNR"       FORCE)
    set(RKAIQ_HAVE_BAYERNR  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR"   FORCE)
    set(RKAIQ_HAVE_GAIN  FALSE CACHE INTERNAL "Build rkaiq's GAIN"      FORCE)
    set(RKAIQ_HAVE_AF   FALSE CACHE INTERNAL "Build rkaiq's AF"       FORCE)
    set(RKAIQ_HAVE_DRC   FALSE CACHE INTERNAL "Build rkaiq's DRC"       FORCE)
    set(RKAIQ_HAVE_DEGAMMA   TRUE CACHE INTERNAL "Build rkaiq's DEGAMMA"       FORCE)
    set(RKAIQ_HAVE_CGC   FALSE CACHE INTERNAL "Build rkaiq's CGC"       FORCE)
    set(RKAIQ_HAVE_AFD   FALSE CACHE INTERNAL "Build rkaiq's AFD"       FORCE)
    set(RKAIQ_HAVE_ASD  FALSE CACHE INTERNAL "Build rkaiq's ASD"       FORCE)
    set(RKAIQ_HAVE_ORB   TRUE CACHE INTERNAL "Build rkaiq's ORB"       FORCE)
    set(RKAIQ_HAVE_EIS   TRUE CACHE INTERNAL "Build rkaiq's EIS"       FORCE)
    set(RKAIQ_HAVE_UVNR TRUE CACHE INTERNAL "Build rkaiq's UVNR"      FORCE)
    set(RKAIQ_HAVE_MFNR  TRUE CACHE INTERNAL "Build rkaiq's MFNR"      FORCE)
    set(RKAIQ_HAVE_ANR   TRUE CACHE INTERNAL "Build rkaiq's ANR"      FORCE)
    set(RKAIQ_HAVE_AMD   TRUE CACHE INTERNAL "Build rkaiq's AMD"      FORCE)
    set(RKAIQ_HAVE_TMO   TRUE CACHE INTERNAL "Build rkaiq's TMO"       FORCE)
    set(RKAIQ_HAVE_FEC  TRUE CACHE INTERNAL "Build rkaiq's FEC"    FORCE)
endif()



if (RKAIQ_ISP_VERSION STREQUAL "39")
    set(RKAIQ_HAVE_AWB_V20  FALSE CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_AWB_V32  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 32"      FORCE)
    set(RKAIQ_HAVE_AWB_V32LT  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32Lite"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   FALSE CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   TRUE  CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   FALSE CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   FALSE CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V03  FALSE CACHE INTERNAL "Build rkaiq's CAC version 03"      FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_CAC_V11  TRUE  CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_CAC_V12  TRUE  CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V2   FALSE CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   FALSE CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_YNR_V22  FALSE  CACHE INTERNAL "Build rkaiq's YNR version 22"      FORCE)
    set(RKAIQ_HAVE_YNR_V24  TRUE  CACHE INTERNAL "Build rkaiq's YNR version 24"      FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   FALSE CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   FALSE CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_CNR_V30  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 30"      FORCE)
    set(RKAIQ_HAVE_CNR_V30_LITE  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 30Lite"      FORCE)
    set(RKAIQ_HAVE_CNR_V31  TRUE  CACHE INTERNAL "Build rkaiq's CNR version 31"      FORCE)
    set(RKAIQ_HAVE_SHARP_V1 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33_LITE FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33Lite"     FORCE)
	set(RKAIQ_HAVE_SHARP_V34 TRUE  CACHE INTERNAL "Build rkaiq's SHARP version 34"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V23 FALSE  CACHE INTERNAL "Build rkaiq's BAYER2DNR version 23"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23_LITE  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23Lite"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V30  TRUE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 30"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  TRUE  CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   FALSE  CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_BLC_V32   TRUE  CACHE INTERNAL "Build rkaiq's BLC  version 32"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   FALSE CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_YUVME_V1  TRUE  CACHE INTERNAL "Build rkaiq's YUVME version 1"      FORCE)
    set(RKAIQ_HAVE_PDAF     TRUE CACHE INTERNAL "Build rkaiq's PDAF"                FORCE)
    set(RKAIQ_HAVE_AF_V20   FALSE CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   FALSE CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    set(RKAIQ_ONLY_AF_STATS_V31 FALSE CACHE INTERNAL "Build only AF stats version 31" FORCE)
    set(RKAIQ_HAVE_AF_V32_LITE   FALSE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
    set(RKAIQ_HAVE_AF_V33   TRUE CACHE INTERNAL "Build rkaiq's AF version 32"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1 TRUE  CACHE INTERNAL "Build rkaiq's 3DLUT version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V1   FALSE  CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V2   FALSE  CACHE INTERNAL "Build rkaiq's CCM version 2"       FORCE)
    set(RKAIQ_HAVE_CCM_V3   TRUE  CACHE INTERNAL "Build rkaiq's CCM version 3"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V11   TRUE CACHE INTERNAL "Build rkaiq's GAMMA version 11"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V10   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V10   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V11   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V12   TRUE CACHE INTERNAL "Build rkaiq's MERGE version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V10   FALSE CACHE INTERNAL "Build rkaiq's DRC version 10"       FORCE)
    set(RKAIQ_HAVE_DRC_V11   FALSE CACHE INTERNAL "Build rkaiq's DRC version 11"       FORCE)
    set(RKAIQ_HAVE_DRC_V12   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V12_LITE   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12 lite"       FORCE)
    set(RKAIQ_HAVE_DRC_V20   TRUE CACHE INTERNAL "Build rkaiq's DRC version 20"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V10   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 10"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11_DUO   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11 DUO"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V12   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 12"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V14   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE version 14"       FORCE)
    set(RKAIQ_HAVE_RGBIR_REMOSAIC   TRUE CACHE INTERNAL "Build rkaiq's RGB remosaic"       FORCE)
    set(RKAIQ_HAVE_RGBIR_REMOSAIC_V10   TRUE CACHE INTERNAL "Build rkaiq's RGBIR remosaic version 10"       FORCE)
    set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
    set(RKAIQ_HAVE_WDR_V1   TRUE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
    set(RKAIQ_HAVE_LDCH_V21  TRUE  CACHE INTERNAL "Build rkaiq's LDCH version 21"    FORCE)
    set(RKAIQ_HAVE_CSM_V1   TRUE CACHE INTERNAL "Build rkaiq's CSM version 1"       FORCE)
    set(RKAIQ_HAVE_CGC_V1   TRUE CACHE INTERNAL "Build rkaiq's CGC version 1"       FORCE)
    set(RKAIQ_HAVE_AE_V1   TRUE CACHE INTERNAL "Build rkaiq's AE version 1"       FORCE)
    set(RKAIQ_HAVE_AFD_V1   FALSE CACHE INTERNAL "Build rkaiq's AFD version 1"       FORCE)
    set(RKAIQ_HAVE_AFD_V2   TRUE CACHE INTERNAL "Build rkaiq's AFD version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V1   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2_LITE   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2 lite"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V3   TRUE CACHE INTERNAL "Build rkaiq's DEBAYER version 3"       FORCE)
    set(RKAIQ_HAVE_LSC_V1   FALSE CACHE INTERNAL "Build rkaiq's LSC version 1"       FORCE)
    set(RKAIQ_HAVE_LSC_V2   FALSE CACHE INTERNAL "Build rkaiq's LSC version 2"       FORCE)
    set(RKAIQ_HAVE_LSC_V3   TRUE CACHE INTERNAL "Build rkaiq's LSC version 3"       FORCE)
    set(RKAIQ_HAVE_DPCC_V1   FALSE CACHE INTERNAL "Build rkaiq's DPCC version 1"       FORCE)
    set(RKAIQ_HAVE_DPCC_V2   TRUE CACHE INTERNAL "Build rkaiq's DPCC version 1"       FORCE)
    set(RKAIQ_HAVE_ACP_V10   TRUE CACHE INTERNAL "Build rkaiq's ACP version 10"       FORCE)
    set(RKAIQ_HAVE_AIE_V10   TRUE CACHE INTERNAL "Build rkaiq's AIE version 10"       FORCE)
    set(RKAIQ_HAVE_ASD_V10  FALSE CACHE INTERNAL "Build rkaiq's ASD version 10"       FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "32_lite")
    set(RKAIQ_HAVE_AWB_V20  FALSE CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_AWB_V32  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 32"      FORCE)
    set(RKAIQ_HAVE_AWB_V32LT  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 32Lite"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   FALSE CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   FALSE  CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   FALSE CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   FALSE CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V03  FALSE CACHE INTERNAL "Build rkaiq's CAC version 03"      FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_CAC_V11  FALSE  CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_CAC_V12  FALSE  CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V2   FALSE CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   FALSE CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_YNR_V22  TRUE  CACHE INTERNAL "Build rkaiq's YNR version 22"      FORCE)
    set(RKAIQ_HAVE_YNR_V24  FALSE  CACHE INTERNAL "Build rkaiq's YNR version 24"      FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   FALSE CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   FALSE CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_CNR_V30  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 30"      FORCE)
    set(RKAIQ_HAVE_CNR_V30_LITE  TRUE  CACHE INTERNAL "Build rkaiq's CNR version 30Lite"      FORCE)
    set(RKAIQ_HAVE_CNR_V31  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 31"      FORCE)
    set(RKAIQ_HAVE_SHARP_V1 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33_LITE TRUE  CACHE INTERNAL "Build rkaiq's SHARP version 33Lite"     FORCE)
	set(RKAIQ_HAVE_SHARP_V34 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 34"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V23 FALSE  CACHE INTERNAL "Build rkaiq's BAYER2DNR version 23"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23_LITE  TRUE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23Lite"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V30  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 30"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  TRUE  CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   FALSE  CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_BLC_V32   TRUE  CACHE INTERNAL "Build rkaiq's BLC  version 32"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   FALSE CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_YUVME_V1  FALSE  CACHE INTERNAL "Build rkaiq's YUVME version 1"      FORCE)
    set(RKAIQ_HAVE_PDAF     FALSE CACHE INTERNAL "Build rkaiq's PDAF"                FORCE)
    set(RKAIQ_HAVE_AF_V20   FALSE CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   FALSE CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_ONLY_AF_STATS_V31 FALSE CACHE INTERNAL "Build only AF stats version 31" FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
#    if (NOT RKAIQ_ENABLE_AF)
#        set(RKAIQ_ONLY_AF_STATS_V32_LITE FALSE CACHE INTERNAL "Build only AF stats version 32 lite" FORCE)
#        set(RKAIQ_HAVE_AF_V32_LITE   FALSE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
#    elseif (RKAIQ_HAVE_ONLY_CUSTOM_AF)
#        set(RKAIQ_ONLY_AF_STATS_V32_LITE TRUE CACHE INTERNAL "Build only AF stats version 32 lite" FORCE)
#        set(RKAIQ_HAVE_AF_V32_LITE   FALSE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
#    else()
#        set(RKAIQ_ONLY_AF_STATS_V32_LITE TRUE CACHE INTERNAL "Build only AF stats version 32 lite" FORCE)
#        set(RKAIQ_HAVE_AF_V32_LITE   TRUE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
#    endif()
    set(RKAIQ_HAVE_AF_V32_LITE   TRUE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
    set(RKAIQ_HAVE_AF_V33   FALSE CACHE INTERNAL "Build rkaiq's AF version 33"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1 TRUE  CACHE INTERNAL "Build rkaiq's 3DLUT version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V1   FALSE  CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V2   TRUE  CACHE INTERNAL "Build rkaiq's CCM version 2"       FORCE)
    set(RKAIQ_HAVE_CCM_V3   FALSE  CACHE INTERNAL "Build rkaiq's CCM version 3"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V11   TRUE CACHE INTERNAL "Build rkaiq's GAMMA version 11"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V10   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V10   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V11   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V12   TRUE CACHE INTERNAL "Build rkaiq's MERGE version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V10   FALSE CACHE INTERNAL "Build rkaiq's DRC version 10"       FORCE)
    set(RKAIQ_HAVE_DRC_V11   FALSE CACHE INTERNAL "Build rkaiq's DRC version 11"       FORCE)
    set(RKAIQ_HAVE_DRC_V12   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V12_LITE   TRUE CACHE INTERNAL "Build rkaiq's DRC version 12 lite"       FORCE)
    set(RKAIQ_HAVE_DRC_V20   FALSE CACHE INTERNAL "Build rkaiq's DRC version 20"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V10   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 10"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11_DUO   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11 DUO"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V12   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE version 12"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V14   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 14"       FORCE)
    set(RKAIQ_HAVE_RGBIR_REMOSAIC   FALSE CACHE INTERNAL "Build rkaiq's RGB remosaic"       FORCE)
    set(RKAIQ_HAVE_RGBIR_REMOSAIC_V10   FALSE CACHE INTERNAL "Build rkaiq's RGBIR remosaic version 10"       FORCE)
    set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
    set(RKAIQ_HAVE_WDR_V1   TRUE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
    set(RKAIQ_HAVE_LDCH_V21  TRUE  CACHE INTERNAL "Build rkaiq's LDCH version 21"    FORCE)
    set(RKAIQ_HAVE_CSM_V1   TRUE CACHE INTERNAL "Build rkaiq's CSM version 1"       FORCE)
    set(RKAIQ_HAVE_CGC_V1   TRUE CACHE INTERNAL "Build rkaiq's CGC version 1"       FORCE)
    set(RKAIQ_HAVE_AE_V1   TRUE CACHE INTERNAL "Build rkaiq's AE version 1"       FORCE)
    set(RKAIQ_HAVE_AFD_V1   FALSE CACHE INTERNAL "Build rkaiq's AFD version 1"       FORCE)
    set(RKAIQ_HAVE_AFD_V2   FALSE CACHE INTERNAL "Build rkaiq's AFD version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V1   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2_LITE   TRUE CACHE INTERNAL "Build rkaiq's DEBAYER version 2 lite"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V3   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 3"       FORCE)
    set(RKAIQ_HAVE_LSC_V1   FALSE CACHE INTERNAL "Build rkaiq's LSC version 1"       FORCE)
    set(RKAIQ_HAVE_LSC_V2   FALSE CACHE INTERNAL "Build rkaiq's LSC version 2"       FORCE)
    set(RKAIQ_HAVE_LSC_V3   TRUE CACHE INTERNAL "Build rkaiq's LSC version 3"       FORCE)
    set(RKAIQ_HAVE_DPCC_V1   TRUE CACHE INTERNAL "Build rkaiq's DPCC version 1"       FORCE)
    set(RKAIQ_HAVE_ACP_V10   TRUE CACHE INTERNAL "Build rkaiq's ACP version 10"       FORCE)
    set(RKAIQ_HAVE_AIE_V10   TRUE CACHE INTERNAL "Build rkaiq's AIE version 10"       FORCE)
    set(RKAIQ_HAVE_ASD_V10  FALSE CACHE INTERNAL "Build rkaiq's ASD version 10"       FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "32")
    set(RKAIQ_HAVE_AWB_V20  FALSE CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_AWB_V32  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 32"      FORCE)
    set(RKAIQ_HAVE_AWB_V32LT  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32Lite"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   FALSE CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   TRUE  CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   FALSE CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   FALSE CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V03  FALSE CACHE INTERNAL "Build rkaiq's CAC version 03"      FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_CAC_V11  TRUE  CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_CAC_V12  FALSE  CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V2   FALSE CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   FALSE CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_YNR_V22  TRUE  CACHE INTERNAL "Build rkaiq's YNR version 22"      FORCE)
    set(RKAIQ_HAVE_YNR_V24  FALSE  CACHE INTERNAL "Build rkaiq's YNR version 24"      FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   FALSE CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   FALSE CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_CNR_V30  TRUE  CACHE INTERNAL "Build rkaiq's CNR version 30"      FORCE)
    set(RKAIQ_HAVE_CNR_V30_LITE  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 30Lite"      FORCE)
    set(RKAIQ_HAVE_CNR_V31  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 31"      FORCE)
    set(RKAIQ_HAVE_SHARP_V1 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33 TRUE  CACHE INTERNAL "Build rkaiq's SHARP version 33"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33_LITE FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33Lite"     FORCE)
	set(RKAIQ_HAVE_SHARP_V34 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 34"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V23 TRUE  CACHE INTERNAL "Build rkaiq's BAYER2DNR version 23"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23  TRUE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23_LITE  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23Lite"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V30  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 30"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  TRUE  CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   FALSE  CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_BLC_V32   TRUE  CACHE INTERNAL "Build rkaiq's BLC  version 32"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   FALSE CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_YUVME_V1  FALSE  CACHE INTERNAL "Build rkaiq's YUVME version 1"      FORCE)
    set(RKAIQ_HAVE_PDAF     FALSE CACHE INTERNAL "Build rkaiq's PDAF"                FORCE)
    set(RKAIQ_HAVE_AF_V20   FALSE CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   FALSE CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    if (NOT RKAIQ_ENABLE_AF)
        set(RKAIQ_ONLY_AF_STATS_V31 FALSE CACHE INTERNAL "Build only AF stats version 31" FORCE)
        set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    elseif (RKAIQ_HAVE_ONLY_CUSTOM_AF)
        set(RKAIQ_ONLY_AF_STATS_V31 TRUE CACHE INTERNAL "Build only AF stats version 31" FORCE)
        set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    else()
        set(RKAIQ_ONLY_AF_STATS_V31 TRUE CACHE INTERNAL "Build only AF stats version 31" FORCE)
        set(RKAIQ_HAVE_AF_V31   TRUE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    endif()
    set(RKAIQ_HAVE_AF_V32_LITE   FALSE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
    set(RKAIQ_HAVE_AF_V33   FALSE CACHE INTERNAL "Build rkaiq's AF version 33"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1 TRUE  CACHE INTERNAL "Build rkaiq's 3DLUT version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V1   FALSE  CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V2   TRUE  CACHE INTERNAL "Build rkaiq's CCM version 2"       FORCE)
    set(RKAIQ_HAVE_CCM_V3   FALSE  CACHE INTERNAL "Build rkaiq's CCM version 3"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V11   TRUE CACHE INTERNAL "Build rkaiq's GAMMA version 11"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V10   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V10   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V11   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V12   TRUE CACHE INTERNAL "Build rkaiq's MERGE version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V10   FALSE CACHE INTERNAL "Build rkaiq's DRC version 10"       FORCE)
    set(RKAIQ_HAVE_DRC_V11   FALSE CACHE INTERNAL "Build rkaiq's DRC version 11"       FORCE)
    set(RKAIQ_HAVE_DRC_V12   TRUE CACHE INTERNAL "Build rkaiq's DRC version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V12_LITE   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12 lite"       FORCE)
    set(RKAIQ_HAVE_DRC_V20   FALSE CACHE INTERNAL "Build rkaiq's DRC version 20"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V10   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 10"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11_DUO   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11 DUO"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V12   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE version 12"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V14   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 14"       FORCE)
    set(RKAIQ_HAVE_RGBIR_REMOSAIC   FALSE CACHE INTERNAL "Build rkaiq's RGB remosaic"       FORCE)
    set(RKAIQ_HAVE_RGBIR_REMOSAIC_V10   FALSE CACHE INTERNAL "Build rkaiq's RGBIR remosaic version 10"       FORCE)
    set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
    set(RKAIQ_HAVE_WDR_V1   TRUE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
    set(RKAIQ_HAVE_LDCH_V21  TRUE  CACHE INTERNAL "Build rkaiq's LDCH version 21"    FORCE)
    set(RKAIQ_HAVE_CSM_V1   TRUE CACHE INTERNAL "Build rkaiq's CSM version 1"       FORCE)
    set(RKAIQ_HAVE_CGC_V1   TRUE CACHE INTERNAL "Build rkaiq's CGC version 1"       FORCE)
    set(RKAIQ_HAVE_AE_V1   TRUE CACHE INTERNAL "Build rkaiq's AE version 1"       FORCE)
    set(RKAIQ_HAVE_AFD_V1   FALSE CACHE INTERNAL "Build rkaiq's AFD version 1"       FORCE)
    set(RKAIQ_HAVE_AFD_V2   TRUE CACHE INTERNAL "Build rkaiq's AFD version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V1   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2   TRUE CACHE INTERNAL "Build rkaiq's DEBAYER version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2_LITE   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2 lite"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V3   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 3"       FORCE)
    set(RKAIQ_HAVE_LSC_V1   FALSE CACHE INTERNAL "Build rkaiq's LSC version 1"       FORCE)
    set(RKAIQ_HAVE_LSC_V2   FALSE CACHE INTERNAL "Build rkaiq's LSC version 2"       FORCE)
    set(RKAIQ_HAVE_LSC_V3   TRUE CACHE INTERNAL "Build rkaiq's LSC version 3"       FORCE)
    set(RKAIQ_HAVE_DPCC_V1   TRUE CACHE INTERNAL "Build rkaiq's DPCC version 1"       FORCE)
    set(RKAIQ_HAVE_ACP_V10   TRUE CACHE INTERNAL "Build rkaiq's ACP version 10"       FORCE)
    set(RKAIQ_HAVE_AIE_V10   TRUE CACHE INTERNAL "Build rkaiq's AIE version 10"       FORCE)
    set(RKAIQ_HAVE_ASD_V10  FALSE CACHE INTERNAL "Build rkaiq's ASD version 10"       FORCE)
    set(RKAIQ_HAVE_DEGAMMA_V1 FALSE CACHE INTERNAL "Build rkaiq's DEGAMMA version 1"     FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "30")
    set(RKAIQ_HAVE_AWB_V20  FALSE CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_AWB_V32  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32"      FORCE)
    set(RKAIQ_HAVE_AWB_V32LT  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32Lite"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   FALSE CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   TRUE  CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   FALSE CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   FALSE CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V03  TRUE CACHE INTERNAL "Build rkaiq's CAC version 03"      FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_CAC_V11  FALSE CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_CAC_V12  FALSE  CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V2   FALSE CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   TRUE  CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_YNR_V22  FALSE CACHE INTERNAL "Build rkaiq's YNR version 22"      FORCE)
    set(RKAIQ_HAVE_YNR_V24  FALSE  CACHE INTERNAL "Build rkaiq's YNR version 24"      FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   FALSE CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   TRUE  CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_CNR_V30  FALSE CACHE INTERNAL "Build rkaiq's CNR version 30"      FORCE)
    set(RKAIQ_HAVE_CNR_V30_LITE  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 30Lite"      FORCE)
    set(RKAIQ_HAVE_CNR_V31  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 31"      FORCE)
    set(RKAIQ_HAVE_SHARP_V1 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 TRUE  CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33_LITE FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33Lite"     FORCE)
	set(RKAIQ_HAVE_SHARP_V34 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 34"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  TRUE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   TRUE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V23  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 23"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 23"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23_LITE  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23Lite"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V30  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 30"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  TRUE  CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   TRUE  CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_BLC_V32   FALSE  CACHE INTERNAL "Build rkaiq's BLC  version 32"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   FALSE CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_YUVME_V1  FALSE  CACHE INTERNAL "Build rkaiq's YUVME version 1"      FORCE)
    set(RKAIQ_HAVE_PDAF     TRUE  CACHE INTERNAL "Build rkaiq's PDAF"                FORCE)
    set(RKAIQ_HAVE_AF_V20   FALSE CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   TRUE  CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    set(RKAIQ_HAVE_AF_V32_LITE   FALSE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
    set(RKAIQ_HAVE_AF_V33   FALSE CACHE INTERNAL "Build rkaiq's AF version 33"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1   TRUE CACHE INTERNAL "Build rkaiq's 3DLUT version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V1   TRUE CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V2   FALSE CACHE INTERNAL "Build rkaiq's CCM version 2"       FORCE)
    set(RKAIQ_HAVE_CCM_V3   FALSE  CACHE INTERNAL "Build rkaiq's CCM version 3"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V11   TRUE CACHE INTERNAL "Build rkaiq's GAMMA version 11"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V10   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V10   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V11   TRUE CACHE INTERNAL "Build rkaiq's MERGE version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V12   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V10   FALSE CACHE INTERNAL "Build rkaiq's DRC version 10"       FORCE)
    set(RKAIQ_HAVE_DRC_V11   TRUE CACHE INTERNAL "Build rkaiq's DRC version 11"       FORCE)
    set(RKAIQ_HAVE_DRC_V12   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V12_LITE   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12 lite"       FORCE)
    set(RKAIQ_HAVE_DRC_V20   FALSE CACHE INTERNAL "Build rkaiq's DRC version 20"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V10   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 10"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11_DUO   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE version 11 DUO"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V12   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 12"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V14   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 14"       FORCE)
    set(RKAIQ_HAVE_RGBIR_REMOSAIC   FALSE CACHE INTERNAL "Build rkaiq's RGB remosaic"       FORCE)
    set(RKAIQ_HAVE_RGBIR_REMOSAIC_V10   FALSE CACHE INTERNAL "Build rkaiq's RGBIR remosaic version 10"       FORCE)
    set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
    set(RKAIQ_HAVE_WDR_V1   TRUE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
    set(RKAIQ_HAVE_LDCH_V10  TRUE  CACHE INTERNAL "Build rkaiq's LDCH version 10"    FORCE)
	set(RKAIQ_HAVE_FEC_V10  FALSE CACHE INTERNAL "Build rkaiq's FEC version 10"    FORCE)
    set(RKAIQ_HAVE_CSM_V1   TRUE CACHE INTERNAL "Build rkaiq's CSM version 1"       FORCE)
    set(RKAIQ_HAVE_CGC_V1   TRUE CACHE INTERNAL "Build rkaiq's CGC version 1"       FORCE)
    set(RKAIQ_HAVE_AE_V1   TRUE CACHE INTERNAL "Build rkaiq's AE version 1"       FORCE)
    set(RKAIQ_HAVE_AFD_V1   FALSE CACHE INTERNAL "Build rkaiq's AFD version 1"       FORCE)
    set(RKAIQ_HAVE_AFD_V2   TRUE CACHE INTERNAL "Build rkaiq's AFD version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V1   TRUE CACHE INTERNAL "Build rkaiq's DEBAYER version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2_LITE   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2 lite"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V3   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 3"       FORCE)
    set(RKAIQ_HAVE_LSC_V1   FALSE CACHE INTERNAL "Build rkaiq's LSC version 1"       FORCE)
    set(RKAIQ_HAVE_LSC_V2   TRUE CACHE INTERNAL "Build rkaiq's LSC version 2"       FORCE)
    set(RKAIQ_HAVE_LSC_V3   FALSE CACHE INTERNAL "Build rkaiq's LSC version 3"       FORCE)
    set(RKAIQ_HAVE_DPCC_V1   TRUE CACHE INTERNAL "Build rkaiq's DPCC version 1"       FORCE)
    set(RKAIQ_HAVE_ACP_V10   TRUE CACHE INTERNAL "Build rkaiq's ACP version 10"       FORCE)
    set(RKAIQ_HAVE_AIE_V10   TRUE CACHE INTERNAL "Build rkaiq's AIE version 10"       FORCE)
    set(RKAIQ_HAVE_ASD_V10   FALSE CACHE INTERNAL "Build rkaiq's ASD version 10"       FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "21")
    set(RKAIQ_HAVE_AWB_V20  FALSE CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   FALSE CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_AWB_V32  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32"      FORCE)
    set(RKAIQ_HAVE_AWB_V32LT  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32Lite"      FORCE)
    set(RKAIQ_HAVE_GIC_V2   TRUE  CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   FALSE CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   FALSE CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V03  FALSE CACHE INTERNAL "Build rkaiq's CAC version 03"      FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_CAC_V11  FALSE CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_CAC_V12  FALSE  CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V2   TRUE  CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   FALSE CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_YNR_V22  FALSE CACHE INTERNAL "Build rkaiq's YNR version 22"      FORCE)
    set(RKAIQ_HAVE_YNR_V24  FALSE  CACHE INTERNAL "Build rkaiq's YNR version 24"      FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   TRUE  CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   FALSE CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_CNR_V30  FALSE CACHE INTERNAL "Build rkaiq's CNR version 30"      FORCE)
    set(RKAIQ_HAVE_CNR_V30_LITE  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 30Lite"      FORCE)
    set(RKAIQ_HAVE_CNR_V31  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 31"      FORCE)
    set(RKAIQ_HAVE_SHARP_V1 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 TRUE  CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33_LITE FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33Lite"     FORCE)
	set(RKAIQ_HAVE_SHARP_V34 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 34"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  TRUE  CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V23  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 23"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 23"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23_LITE  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23Lite"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V30  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 30"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   TRUE  CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_BLC_V32   FALSE  CACHE INTERNAL "Build rkaiq's BLC  version 32"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   FALSE CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_PDAF     FALSE CACHE INTERNAL "Build rkaiq's PDAF"                FORCE)
    set(RKAIQ_HAVE_YUVME_V1  FALSE  CACHE INTERNAL "Build rkaiq's YUVME version 1"      FORCE)
    set(RKAIQ_HAVE_AF_V20   TRUE  CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   FALSE CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    set(RKAIQ_HAVE_AF_V32_LITE   FALSE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
    set(RKAIQ_HAVE_AF_V33   FALSE CACHE INTERNAL "Build rkaiq's AF version 33"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1 TRUE  CACHE INTERNAL "Build rkaiq's 3DLUT version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V1   TRUE  CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V2   FALSE CACHE INTERNAL "Build rkaiq's CCM version 2"       FORCE)
    set(RKAIQ_HAVE_CCM_V3   FALSE  CACHE INTERNAL "Build rkaiq's CCM version 3"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V10   TRUE CACHE INTERNAL "Build rkaiq's GAMMA version 10"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V11   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V10   TRUE CACHE INTERNAL "Build rkaiq's MERGE version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V11   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V12   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V10   TRUE CACHE INTERNAL "Build rkaiq's DRC version 10"       FORCE)
    set(RKAIQ_HAVE_DRC_V11   FALSE CACHE INTERNAL "Build rkaiq's DRC version 11"       FORCE)
    set(RKAIQ_HAVE_DRC_V12   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V12_LITE   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12 lite"       FORCE)
    set(RKAIQ_HAVE_DRC_V20   FALSE CACHE INTERNAL "Build rkaiq's DRC version 20"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V10   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 10"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE version 11"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11_DUO   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11 DUO"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V12   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 12"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V14   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 14"       FORCE)
    set(RKAIQ_HAVE_RGBIR_REMOSAIC   FALSE CACHE INTERNAL "Build rkaiq's RGB remosaic"       FORCE)
    set(RKAIQ_HAVE_RGBIR_REMOSAIC_V10   FALSE CACHE INTERNAL "Build rkaiq's RGBIR remosaic version 10"       FORCE)
    set(RKAIQ_HAVE_DEGAMMA_V1   TRUE CACHE INTERNAL "Build rkaiq's DEGAMMA version 1"       FORCE)
    set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
    set(RKAIQ_HAVE_WDR_V1   TRUE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
    set(RKAIQ_HAVE_LDCH_V10  TRUE  CACHE INTERNAL "Build rkaiq's LDCH version 10"    FORCE)
    set(RKAIQ_HAVE_FEC_V10  FALSE  CACHE INTERNAL "Build rkaiq's FEC version 10"    FORCE)
    set(RKAIQ_HAVE_CSM_V1   TRUE CACHE INTERNAL "Build rkaiq's CSM version 1"       FORCE)
    set(RKAIQ_HAVE_CGC_V1   TRUE CACHE INTERNAL "Build rkaiq's CGC version 1"       FORCE)
    set(RKAIQ_HAVE_AE_V1   TRUE CACHE INTERNAL "Build rkaiq's AE version 1"       FORCE)
    set(RKAIQ_HAVE_AFD_V1   FALSE CACHE INTERNAL "Build rkaiq's AFD version 1"       FORCE)
    set(RKAIQ_HAVE_AFD_V2   FALSE CACHE INTERNAL "Build rkaiq's AFD version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V1   TRUE CACHE INTERNAL "Build rkaiq's DEBAYER version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2_LITE   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2 lite"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V3   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 3"       FORCE)
    set(RKAIQ_HAVE_LSC_V1   TRUE CACHE INTERNAL "Build rkaiq's LSC version 1"       FORCE)
    set(RKAIQ_HAVE_LSC_V2   FALSE CACHE INTERNAL "Build rkaiq's LSC version 2"       FORCE)
    set(RKAIQ_HAVE_LSC_V3   FALSE CACHE INTERNAL "Build rkaiq's LSC version 3"       FORCE)
    set(RKAIQ_HAVE_DPCC_V1   TRUE CACHE INTERNAL "Build rkaiq's DPCC version 1"       FORCE)
    set(RKAIQ_HAVE_ACP_V10   TRUE CACHE INTERNAL "Build rkaiq's ACP version 10"       FORCE)
    set(RKAIQ_HAVE_AIE_V10   TRUE CACHE INTERNAL "Build rkaiq's AIE version 10"       FORCE)
    set(RKAIQ_HAVE_ASD_V10   FALSE CACHE INTERNAL "Build rkaiq's ASD version 10"       FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "20")
    set(RKAIQ_HAVE_AWB_V20  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  FALSE CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_AWB_V32  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32"      FORCE)
    set(RKAIQ_HAVE_AWB_V32LT  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32Lite"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   TRUE  CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   FALSE CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   TRUE  CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   TRUE  CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V03  FALSE CACHE INTERNAL "Build rkaiq's CAC version 03"      FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_CAC_V11  FALSE CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_CAC_V12  FALSE  CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V2   FALSE CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   FALSE CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_YNR_V22  FALSE CACHE INTERNAL "Build rkaiq's YNR version 22"      FORCE)
    set(RKAIQ_HAVE_YNR_V24  FALSE  CACHE INTERNAL "Build rkaiq's YNR version 24"      FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   FALSE CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   FALSE CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_CNR_V30  FALSE CACHE INTERNAL "Build rkaiq's CNR version 30"      FORCE)
    set(RKAIQ_HAVE_CNR_V30_LITE  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 30Lite"      FORCE)
    set(RKAIQ_HAVE_CNR_V31  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 31"      FORCE)
    set(RKAIQ_HAVE_SHARP_V1 TRUE  CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33_LITE FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33Lite"     FORCE)
	set(RKAIQ_HAVE_SHARP_V34 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 34"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V23  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 23"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 23"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23_LITE  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23Lite"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V30  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 30"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   TRUE  CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_BLC_V32   FALSE  CACHE INTERNAL "Build rkaiq's BLC  version 32"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   TRUE  CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_YUVME_V1  FALSE  CACHE INTERNAL "Build rkaiq's YUVME version 1"      FORCE)
    set(RKAIQ_HAVE_PDAF     FALSE CACHE INTERNAL "Build rkaiq's PDAF"                FORCE)
    set(RKAIQ_HAVE_AF_V20   FALSE CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   FALSE CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    set(RKAIQ_HAVE_AF_V32_LITE   FALSE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
    set(RKAIQ_HAVE_AF_V33   FALSE CACHE INTERNAL "Build rkaiq's AF version 33"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1   TRUE CACHE INTERNAL "Build rkaiq's 3DLUT version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V1   TRUE CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V2   FALSE CACHE INTERNAL "Build rkaiq's CCM version 2"       FORCE)
    set(RKAIQ_HAVE_CCM_V3   FALSE  CACHE INTERNAL "Build rkaiq's CCM version 3"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V10   TRUE CACHE INTERNAL "Build rkaiq's GAMMA version 10"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V11   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V10   TRUE CACHE INTERNAL "Build rkaiq's MERGE version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V11   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V12   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V10   FALSE CACHE INTERNAL "Build rkaiq's DRC version 10"       FORCE)
    set(RKAIQ_HAVE_DRC_V11   FALSE CACHE INTERNAL "Build rkaiq's DRC version 11"       FORCE)
    set(RKAIQ_HAVE_DRC_V12   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V12_LITE   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12 lite"       FORCE)
    set(RKAIQ_HAVE_DRC_V20   FALSE CACHE INTERNAL "Build rkaiq's DRC version 20"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V10   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE version 10"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11_DUO   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11 DUO"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V12   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 12"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V14   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 14"       FORCE)
    set(RKAIQ_HAVE_RGBIR_REMOSAIC   FALSE CACHE INTERNAL "Build rkaiq's RGB remosaic"       FORCE)
    set(RKAIQ_HAVE_RGBIR_REMOSAIC_V10   FALSE CACHE INTERNAL "Build rkaiq's RGBIR remosaic version 10"       FORCE)
    set(RKAIQ_HAVE_DEGAMMA_V1   TRUE CACHE INTERNAL "Build rkaiq's DEGAMMA version 1"       FORCE)
    set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
    set(RKAIQ_HAVE_WDR_V1   TRUE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
    set(RKAIQ_HAVE_LDCH_V10  TRUE  CACHE INTERNAL "Build rkaiq's LDCH version 10"    FORCE)
    set(RKAIQ_HAVE_FEC_V10  TRUE  CACHE INTERNAL "Build rkaiq's FEC version 10"    FORCE)
    set(RKAIQ_HAVE_CSM_V1   TRUE CACHE INTERNAL "Build rkaiq's CSM version 1"       FORCE)
    set(RKAIQ_HAVE_CGC_V1   FALSE CACHE INTERNAL "Build rkaiq's CGC version 1"       FORCE)
    set(RKAIQ_HAVE_AE_V1   TRUE CACHE INTERNAL "Build rkaiq's AE version 1"       FORCE)
    set(RKAIQ_HAVE_AFD_V1   FALSE CACHE INTERNAL "Build rkaiq's AFD version 1"       FORCE)
    set(RKAIQ_HAVE_AFD_V2   FALSE CACHE INTERNAL "Build rkaiq's AFD version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V1   TRUE CACHE INTERNAL "Build rkaiq's DEBAYER version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2_LITE   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2 lite"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V3   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 3"       FORCE)
    set(RKAIQ_HAVE_LSC_V1   TRUE CACHE INTERNAL "Build rkaiq's LSC version 1"       FORCE)
    set(RKAIQ_HAVE_LSC_V2   FALSE CACHE INTERNAL "Build rkaiq's LSC version 2"       FORCE)
    set(RKAIQ_HAVE_LSC_V3   FALSE CACHE INTERNAL "Build rkaiq's LSC version 3"       FORCE)
    set(RKAIQ_HAVE_DPCC_V1   TRUE CACHE INTERNAL "Build rkaiq's DPCC version 1"       FORCE)
    set(RKAIQ_HAVE_ACP_V10   TRUE CACHE INTERNAL "Build rkaiq's ACP version 10"       FORCE)
    set(RKAIQ_HAVE_AIE_V10   TRUE CACHE INTERNAL "Build rkaiq's AIE version 10"       FORCE)
    set(RKAIQ_HAVE_ASD_V10   FALSE CACHE INTERNAL "Build rkaiq's ASD version 10"       FORCE)
else()
    set(RKAIQ_HAVE_AWB_V20  FALSE CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  FALSE CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_AWB_V32  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32"      FORCE)
    set(RKAIQ_HAVE_AWB_V32LT  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32Lite"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   FALSE CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   FALSE CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   FALSE CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   FALSE CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V03  FALSE CACHE INTERNAL "Build rkaiq's CAC version 03"      FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_CAC_V11  FALSE CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_CAC_V12  FALSE  CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V2   FALSE CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   FALSE CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_YNR_V22  FALSE CACHE INTERNAL "Build rkaiq's YNR version 22"      FORCE)
    set(RKAIQ_HAVE_YNR_V24  FALSE  CACHE INTERNAL "Build rkaiq's YNR version 24"      FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   FALSE CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   FALSE CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_CNR_V30  FALSE CACHE INTERNAL "Build rkaiq's CNR version 30"      FORCE)
    set(RKAIQ_HAVE_CNR_V30_LITE  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 30Lite"      FORCE)
    set(RKAIQ_HAVE_CNR_V31  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 31"      FORCE)
    set(RKAIQ_HAVE_SHARP_V1 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33_LITE FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33Lite"     FORCE)
	set(RKAIQ_HAVE_SHARP_V34 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 34"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V23  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 23"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23  FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 23" FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23_LITE  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23Lite"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V30  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 30"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   FALSE CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_BLC_V32   FALSE  CACHE INTERNAL "Build rkaiq's BLC  version 32"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   FALSE CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_YUVME_V1  FALSE  CACHE INTERNAL "Build rkaiq's YUVME version 1"      FORCE)
    set(RKAIQ_HAVE_PDAF     FALSE CACHE INTERNAL "Build rkaiq's PDAF"                FORCE)
    set(RKAIQ_HAVE_AF_V20   FALSE CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   FALSE CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    set(RKAIQ_HAVE_AF_V32_LITE   FALSE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
    set(RKAIQ_HAVE_AF_V33   FALSE CACHE INTERNAL "Build rkaiq's AF version 33"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1 FALSE CACHE INTERNAL "Build rkaiq's 3DLUT version 1"     FORCE)
    set(RKAIQ_HAVE_CCM_V1   FALSE CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V2   FALSE CACHE INTERNAL "Build rkaiq's CCM version 2"       FORCE)
    set(RKAIQ_HAVE_CCM_V3   FALSE  CACHE INTERNAL "Build rkaiq's CCM version 3"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V10   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 10"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V11   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V10   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V11   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V12   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V10   FALSE CACHE INTERNAL "Build rkaiq's DRC version 10"       FORCE)
    set(RKAIQ_HAVE_DRC_V11   FALSE CACHE INTERNAL "Build rkaiq's DRC version 11"       FORCE)
    set(RKAIQ_HAVE_DRC_V12   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V12_LITE   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12 lite"       FORCE)
    set(RKAIQ_HAVE_DRC_V20   FALSE CACHE INTERNAL "Build rkaiq's DRC version 20"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V10   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 10"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11_DUO   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11 DUO"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V12   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 12"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V14   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 14"       FORCE)
    set(RKAIQ_HAVE_RGBIR_REMOSAIC   FALSE CACHE INTERNAL "Build rkaiq's RGB remosaic"       FORCE)
    set(RKAIQ_HAVE_RGBIR_REMOSAIC_V10   FALSE CACHE INTERNAL "Build rkaiq's RGBIR remosaic version 10"       FORCE)
    set(RKAIQ_HAVE_DEGAMMA_V1   FALSE CACHE INTERNAL "Build rkaiq's DEGAMMA version 1"       FORCE)
    set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
    set(RKAIQ_HAVE_WDR_V1   FALSE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
    set(RKAIQ_HAVE_LDCH_V10  FALSE  CACHE INTERNAL "Build rkaiq's LDCH version 10"    FORCE)
    set(RKAIQ_HAVE_FEC_V10  FALSE  CACHE INTERNAL "Build rkaiq's FEC version 10"    FORCE)
    set(RKAIQ_HAVE_CSM_V1   FALSE CACHE INTERNAL "Build rkaiq's CSM version 1"       FORCE)
    set(RKAIQ_HAVE_CGC_V1   FALSE CACHE INTERNAL "Build rkaiq's CGC version 1"       FORCE)
    set(RKAIQ_HAVE_AE_V1   FALSE CACHE INTERNAL "Build rkaiq's AE version 1"       FORCE)
    set(RKAIQ_HAVE_AFD_V1   FALSE CACHE INTERNAL "Build rkaiq's AFD version 1"       FORCE)
    set(RKAIQ_HAVE_AFD_V2   FALSE CACHE INTERNAL "Build rkaiq's AFD version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V1   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2_LITE   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2 lite"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V3   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 3"       FORCE)
    set(RKAIQ_HAVE_LSC_V1   FALSE CACHE INTERNAL "Build rkaiq's LSC version 1"       FORCE)
    set(RKAIQ_HAVE_LSC_V2   FALSE CACHE INTERNAL "Build rkaiq's LSC version 2"       FORCE)
    set(RKAIQ_HAVE_LSC_V3   FALSE CACHE INTERNAL "Build rkaiq's LSC version 3"       FORCE)
    set(RKAIQ_HAVE_DPCC_V1   FALSE CACHE INTERNAL "Build rkaiq's DPCC version 1"       FORCE)
    set(RKAIQ_HAVE_ACP_V10   FALSE CACHE INTERNAL "Build rkaiq's ACP version 10"       FORCE)
    set(RKAIQ_HAVE_AIE_V10   FALSE CACHE INTERNAL "Build rkaiq's AIE version 10"       FORCE)
    set(RKAIQ_HAVE_ASD_V10   FALSE CACHE INTERNAL "Build rkaiq's ASD version 10"       FORCE)
endif()
