include(CMakeDependentOption)

cmake_dependent_option(RKAIQ_BUILD_DOCS "Build all of rkaiq's documents." OFF "WIN32" OFF)
cmake_dependent_option(RKAIQ_BUILD_TESTS "Build all of rkaiq's own tests." OFF "WIN32" OFF)
cmake_dependent_option(RKAIQ_BUILD_EXAMPLES "Build all of rkaiq's own examples." OFF "WIN32" OFF)
cmake_dependent_option(RKAIQ_ENABLE_ASAN "Build libraries/executable with address santilizer" OFF "WIN32" OFF)
cmake_dependent_option(RKAIQ_ENABLE_SIMULATOR "Build simulator for algos run on PC" OFF "WIN32" OFF)
set(RKAIQ_ENABLE_PARSER_V1   FALSE CACHE INTERNAL "Build rkaiq's old xml parser")
set(RKAIQ_ENABLE_CAMGROUP    FALSE CACHE INTERNAL "Build rkaiq's camera group algorithms")
set(RKAIQ_ENABLE_LIBDRM      TRUE  CACHE INTERNAL "Build rkaiq with libdrm")
set(RKAIQ_HAVE_FAKECAM       FALSE CACHE INTERNAL "Build rkaiq's Fake Cam")
set(RKAIQ_HAVE_SPSTREAM      FALSE CACHE INTERNAL "Build rkaiq's SP Stream")
set(RKAIQ_HAVE_THUMBNAILS    FALSE CACHE INTERNAL "Build rkaiq's Thumbnails Service")
set(RKAIQ_HAVE_MULTIISP      FALSE CACHE INTERNAL "Build rkaiq's Dual ISP")
set(RKAIQ_ENABLE_AF          FALSE CACHE INTERNAL "Build rkaiq's AF algorithm")
set(RKAIQ_HAVE_ONLY_CUSTOM_AF FALSE CACHE INTERNAL "Build AF stats for custom algorithm")
set(RKAIQ_INSTALL_ALGOS_LIB FALSE CACHE INTERNAL "Install algos lib to algos dir")
set(RKAIQ_USE_RAWSTREAM_LIB FALSE CACHE INTERNAL "Build rkaiq with libstream")

if (RKAIQ_TARGET_SOC STREQUAL "rk3562")
    set(RKAIQ_ISP_VERSION        "32_lite"  CACHE INTERNAL "ISP hardware version 32 lite"     FORCE)
elseif (RKAIQ_TARGET_SOC STREQUAL "rv1106")
    set(RKAIQ_ISP_VERSION        "32"  CACHE INTERNAL "ISP hardware version 32"               FORCE)
elseif (RKAIQ_TARGET_SOC STREQUAL "rk3588")
    set(RKAIQ_ISP_VERSION        "30"  CACHE INTERNAL "ISP hardware version 30"               FORCE)
    set(RKAIQ_ENABLE_CAMGROUP    TRUE  CACHE INTERNAL "Build rkaiq's camera group algorithms" FORCE)
    set(RKAIQ_HAVE_THUMBNAILS    TRUE  CACHE INTERNAL "Build rkaiq's Thumbnails Service"      FORCE)
    set(RKAIQ_HAVE_MULTIISP      TRUE  CACHE INTERNAL "Build rkaiq's Dual ISP"                FORCE)
elseif (RKAIQ_TARGET_SOC STREQUAL "rk356x")
    set(RKAIQ_ISP_VERSION        "21"  CACHE INTERNAL "ISP hardware version 21"               FORCE)
elseif (RKAIQ_TARGET_SOC STREQUAL "rv1109")
    set(RKAIQ_ISP_VERSION        "20"  CACHE INTERNAL "ISP hardware version 20"               FORCE)
else()
    set(RKAIQ_ISP_VERSION        "30"  CACHE INTERNAL "No ISP hardware version specificed"    FORCE)
    message(WARNING "RKAIQ_TARGET_SOC SHOULD be set")
endif()

message(STATUS "Building ISP v${RKAIQ_ISP_VERSION} rkaiq for soc ${RKAIQ_TARGET_SOC}")

if (ISP_HW_VERSION STRLESS "-DISP_HW_V20")
    message(FATAL_ERROR "ISP_HW_VERSION MUST be set")
endif()

if (RKAIQ_ISP_VERSION STREQUAL "32_lite")
    set(RKAIQ_HAVE_AWB_V20  FALSE CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_AWB_V32  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 32"      FORCE)
    set(RKAIQ_HAVE_AWB_V32LT  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 32Lite"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   FALSE CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   FALSE  CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   FALSE CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   FALSE CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V03  FALSE CACHE INTERNAL "Build rkaiq's CAC version 03"      FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_CAC_V11  FALSE  CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V2   FALSE CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   FALSE CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_YNR_V22  TRUE  CACHE INTERNAL "Build rkaiq's YNR version 22"      FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   FALSE CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   FALSE CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_CNR_V30  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 30"      FORCE)
    set(RKAIQ_HAVE_CNR_V30_LITE  TRUE  CACHE INTERNAL "Build rkaiq's CNR version 30Lite"      FORCE)
    set(RKAIQ_HAVE_SHARP_V1 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33_LITE TRUE  CACHE INTERNAL "Build rkaiq's SHARP version 33Lite"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V23 FALSE  CACHE INTERNAL "Build rkaiq's BAYER2DNR version 23"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23_LITE  TRUE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23Lite"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  TRUE  CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   FALSE  CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_BLC_V32   TRUE  CACHE INTERNAL "Build rkaiq's BLC  version 32"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   FALSE CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_PDAF     FALSE CACHE INTERNAL "Build rkaiq's PDAF"                FORCE)
    set(RKAIQ_HAVE_AF_V20   FALSE CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   FALSE CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_ONLY_AF_STATS_V31 FALSE CACHE INTERNAL "Build only AF stats version 31" FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
#    if (NOT RKAIQ_ENABLE_AF)
#        set(RKAIQ_ONLY_AF_STATS_V32_LITE FALSE CACHE INTERNAL "Build only AF stats version 32 lite" FORCE)
#        set(RKAIQ_HAVE_AF_V32_LITE   FALSE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
#    elseif (RKAIQ_HAVE_ONLY_CUSTOM_AF)
#        set(RKAIQ_ONLY_AF_STATS_V32_LITE TRUE CACHE INTERNAL "Build only AF stats version 32 lite" FORCE)
#        set(RKAIQ_HAVE_AF_V32_LITE   FALSE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
#    else()
#        set(RKAIQ_ONLY_AF_STATS_V32_LITE TRUE CACHE INTERNAL "Build only AF stats version 32 lite" FORCE)
#        set(RKAIQ_HAVE_AF_V32_LITE   TRUE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
#    endif()
    set(RKAIQ_HAVE_AF_V32_LITE   TRUE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1 TRUE  CACHE INTERNAL "Build rkaiq's 3DLUT version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V1   FALSE  CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V2   TRUE  CACHE INTERNAL "Build rkaiq's CCM version 2"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V11   TRUE CACHE INTERNAL "Build rkaiq's GAMMA version 11"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V10   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V10   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V11   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V12   TRUE CACHE INTERNAL "Build rkaiq's MERGE version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V10   FALSE CACHE INTERNAL "Build rkaiq's DRC version 10"       FORCE)
    set(RKAIQ_HAVE_DRC_V11   FALSE CACHE INTERNAL "Build rkaiq's DRC version 11"       FORCE)
    set(RKAIQ_HAVE_DRC_V12   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V12_LITE   TRUE CACHE INTERNAL "Build rkaiq's DRC version 12 lite"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V10   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 10"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11_DUO   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11 DUO"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V12   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE version 12"       FORCE)
    set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
    set(RKAIQ_HAVE_WDR_V1   TRUE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
    set(RKAIQ_HAVE_LDCH_V21  TRUE  CACHE INTERNAL "Build rkaiq's LDCH version 21"    FORCE)
    set(RKAIQ_HAVE_CSM_V1   TRUE CACHE INTERNAL "Build rkaiq's CSM version 1"       FORCE)
    set(RKAIQ_HAVE_CGC_V1   TRUE CACHE INTERNAL "Build rkaiq's CGC version 1"       FORCE)
    set(RKAIQ_HAVE_AE_V1   TRUE CACHE INTERNAL "Build rkaiq's AE version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V1   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2_LITE   TRUE CACHE INTERNAL "Build rkaiq's DEBAYER version 2 lite"       FORCE)
    set(RKAIQ_HAVE_LSC_V1   FALSE CACHE INTERNAL "Build rkaiq's LSC version 1"       FORCE)
    set(RKAIQ_HAVE_LSC_V2   FALSE CACHE INTERNAL "Build rkaiq's LSC version 2"       FORCE)
    set(RKAIQ_HAVE_LSC_V3   TRUE CACHE INTERNAL "Build rkaiq's LSC version 3"       FORCE)
    set(RKAIQ_HAVE_DPCC_V1   TRUE CACHE INTERNAL "Build rkaiq's DPCC version 1"       FORCE)
    set(RKAIQ_HAVE_ACP_V10   TRUE CACHE INTERNAL "Build rkaiq's ACP version 10"       FORCE)
    set(RKAIQ_HAVE_AIE_V10   TRUE CACHE INTERNAL "Build rkaiq's AIE version 10"       FORCE)
    set(RKAIQ_HAVE_ASD_V10  FALSE CACHE INTERNAL "Build rkaiq's ASD version 10"       FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "32")
    set(RKAIQ_HAVE_AWB_V20  FALSE CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_AWB_V32  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 32"      FORCE)
    set(RKAIQ_HAVE_AWB_V32LT  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32Lite"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   FALSE CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   TRUE  CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   FALSE CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   FALSE CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V03  FALSE CACHE INTERNAL "Build rkaiq's CAC version 03"      FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_CAC_V11  TRUE  CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V2   FALSE CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   FALSE CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_YNR_V22  TRUE  CACHE INTERNAL "Build rkaiq's YNR version 22"      FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   FALSE CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   FALSE CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_CNR_V30  TRUE  CACHE INTERNAL "Build rkaiq's CNR version 30"      FORCE)
    set(RKAIQ_HAVE_CNR_V30_LITE  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 30Lite"      FORCE)
    set(RKAIQ_HAVE_SHARP_V1 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33 TRUE  CACHE INTERNAL "Build rkaiq's SHARP version 33"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33_LITE FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33Lite"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V23 TRUE  CACHE INTERNAL "Build rkaiq's BAYER2DNR version 23"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23  TRUE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23_LITE  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23Lite"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  TRUE  CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   FALSE  CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_BLC_V32   TRUE  CACHE INTERNAL "Build rkaiq's BLC  version 32"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   FALSE CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_PDAF     FALSE CACHE INTERNAL "Build rkaiq's PDAF"                FORCE)
    set(RKAIQ_HAVE_AF_V20   FALSE CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   FALSE CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    if (NOT RKAIQ_ENABLE_AF)
        set(RKAIQ_ONLY_AF_STATS_V31 FALSE CACHE INTERNAL "Build only AF stats version 31" FORCE)
        set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    elseif (RKAIQ_HAVE_ONLY_CUSTOM_AF)
        set(RKAIQ_ONLY_AF_STATS_V31 TRUE CACHE INTERNAL "Build only AF stats version 31" FORCE)
        set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    else()
        set(RKAIQ_ONLY_AF_STATS_V31 TRUE CACHE INTERNAL "Build only AF stats version 31" FORCE)
        set(RKAIQ_HAVE_AF_V31   TRUE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    endif()
    set(RKAIQ_HAVE_AF_V32_LITE   FALSE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1 TRUE  CACHE INTERNAL "Build rkaiq's 3DLUT version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V1   FALSE  CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V2   TRUE  CACHE INTERNAL "Build rkaiq's CCM version 2"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V11   TRUE CACHE INTERNAL "Build rkaiq's GAMMA version 11"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V10   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V10   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V11   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V12   TRUE CACHE INTERNAL "Build rkaiq's MERGE version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V10   FALSE CACHE INTERNAL "Build rkaiq's DRC version 10"       FORCE)
    set(RKAIQ_HAVE_DRC_V11   FALSE CACHE INTERNAL "Build rkaiq's DRC version 11"       FORCE)
    set(RKAIQ_HAVE_DRC_V12   TRUE CACHE INTERNAL "Build rkaiq's DRC version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V12_LITE   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12 lite"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V10   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 10"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11_DUO   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11 DUO"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V12   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE version 12"       FORCE)
    set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
    set(RKAIQ_HAVE_WDR_V1   TRUE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
    set(RKAIQ_HAVE_LDCH_V21  TRUE  CACHE INTERNAL "Build rkaiq's LDCH version 21"    FORCE)
    set(RKAIQ_HAVE_CSM_V1   TRUE CACHE INTERNAL "Build rkaiq's CSM version 1"       FORCE)
    set(RKAIQ_HAVE_CGC_V1   TRUE CACHE INTERNAL "Build rkaiq's CGC version 1"       FORCE)
    set(RKAIQ_HAVE_AE_V1   TRUE CACHE INTERNAL "Build rkaiq's AE version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V1   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2   TRUE CACHE INTERNAL "Build rkaiq's DEBAYER version 2"       FORCE)
	set(RKAIQ_HAVE_DEBAYER_V2_LITE   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2 lite"       FORCE)
    set(RKAIQ_HAVE_LSC_V1   FALSE CACHE INTERNAL "Build rkaiq's LSC version 1"       FORCE)
    set(RKAIQ_HAVE_LSC_V2   FALSE CACHE INTERNAL "Build rkaiq's LSC version 2"       FORCE)
    set(RKAIQ_HAVE_LSC_V3   TRUE CACHE INTERNAL "Build rkaiq's LSC version 3"       FORCE)
    set(RKAIQ_HAVE_DPCC_V1   TRUE CACHE INTERNAL "Build rkaiq's DPCC version 1"       FORCE)
    set(RKAIQ_HAVE_ACP_V10   TRUE CACHE INTERNAL "Build rkaiq's ACP version 10"       FORCE)
    set(RKAIQ_HAVE_AIE_V10   TRUE CACHE INTERNAL "Build rkaiq's AIE version 10"       FORCE)
    set(RKAIQ_HAVE_ASD_V10  FALSE CACHE INTERNAL "Build rkaiq's ASD version 10"       FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "30")
    set(RKAIQ_HAVE_AWB_V20  FALSE CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_AWB_V32  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32"      FORCE)
    set(RKAIQ_HAVE_AWB_V32LT  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32Lite"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   FALSE CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   TRUE  CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   FALSE CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   FALSE CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V03  TRUE CACHE INTERNAL "Build rkaiq's CAC version 03"      FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_CAC_V11  FALSE CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V2   FALSE CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   TRUE  CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_YNR_V22  FALSE CACHE INTERNAL "Build rkaiq's YNR version 22"      FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   FALSE CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   TRUE  CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_CNR_V30  FALSE CACHE INTERNAL "Build rkaiq's CNR version 30"      FORCE)
    set(RKAIQ_HAVE_CNR_V30_LITE  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 30Lite"      FORCE)
    set(RKAIQ_HAVE_SHARP_V1 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 TRUE  CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33_LITE FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33Lite"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  TRUE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   TRUE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V23  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 23"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 23"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23_LITE  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23Lite"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  TRUE  CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   TRUE  CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_BLC_V32   FALSE  CACHE INTERNAL "Build rkaiq's BLC  version 32"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   FALSE CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_PDAF     TRUE  CACHE INTERNAL "Build rkaiq's PDAF"                FORCE)
    set(RKAIQ_HAVE_AF_V20   FALSE CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   TRUE  CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    set(RKAIQ_HAVE_AF_V32_LITE   FALSE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1   TRUE CACHE INTERNAL "Build rkaiq's 3DLUT version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V1   TRUE CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V2   FALSE CACHE INTERNAL "Build rkaiq's CCM version 2"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V11   TRUE CACHE INTERNAL "Build rkaiq's GAMMA version 11"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V10   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V10   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V11   TRUE CACHE INTERNAL "Build rkaiq's MERGE version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V12   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V10   FALSE CACHE INTERNAL "Build rkaiq's DRC version 10"       FORCE)
    set(RKAIQ_HAVE_DRC_V11   TRUE CACHE INTERNAL "Build rkaiq's DRC version 11"       FORCE)
    set(RKAIQ_HAVE_DRC_V12   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V12_LITE   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12 lite"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V10   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 10"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11_DUO   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE version 11 DUO"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V12   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 12"       FORCE)
    set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
    set(RKAIQ_HAVE_WDR_V1   TRUE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
    set(RKAIQ_HAVE_LDCH_V10  TRUE  CACHE INTERNAL "Build rkaiq's LDCH version 10"    FORCE)
    set(RKAIQ_HAVE_FEC_V10  TRUE  CACHE INTERNAL "Build rkaiq's FEC version 10"    FORCE)
    set(RKAIQ_HAVE_CSM_V1   TRUE CACHE INTERNAL "Build rkaiq's CSM version 1"       FORCE)
    set(RKAIQ_HAVE_CGC_V1   TRUE CACHE INTERNAL "Build rkaiq's CGC version 1"       FORCE)
    set(RKAIQ_HAVE_AE_V1   TRUE CACHE INTERNAL "Build rkaiq's AE version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V1   TRUE CACHE INTERNAL "Build rkaiq's DEBAYER version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2_LITE   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2 lite"       FORCE)
    set(RKAIQ_HAVE_LSC_V1   FALSE CACHE INTERNAL "Build rkaiq's LSC version 1"       FORCE)
    set(RKAIQ_HAVE_LSC_V2   TRUE CACHE INTERNAL "Build rkaiq's LSC version 2"       FORCE)
    set(RKAIQ_HAVE_LSC_V3   FALSE CACHE INTERNAL "Build rkaiq's LSC version 3"       FORCE)
    set(RKAIQ_HAVE_DPCC_V1   TRUE CACHE INTERNAL "Build rkaiq's DPCC version 1"       FORCE)
    set(RKAIQ_HAVE_ACP_V10   TRUE CACHE INTERNAL "Build rkaiq's ACP version 10"       FORCE)
    set(RKAIQ_HAVE_AIE_V10   TRUE CACHE INTERNAL "Build rkaiq's AIE version 10"       FORCE)
    set(RKAIQ_HAVE_ASD_V10   FALSE CACHE INTERNAL "Build rkaiq's ASD version 10"       FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "21")
    set(RKAIQ_HAVE_AWB_V20  FALSE CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   FALSE CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_AWB_V32  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32"      FORCE)
    set(RKAIQ_HAVE_AWB_V32LT  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32Lite"      FORCE)
    set(RKAIQ_HAVE_GIC_V2   TRUE  CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   FALSE CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   FALSE CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V03  FALSE CACHE INTERNAL "Build rkaiq's CAC version 03"      FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_CAC_V11  FALSE CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V2   TRUE  CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   FALSE CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_YNR_V22  FALSE CACHE INTERNAL "Build rkaiq's YNR version 22"      FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   TRUE  CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   FALSE CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_CNR_V30  FALSE CACHE INTERNAL "Build rkaiq's CNR version 30"      FORCE)
    set(RKAIQ_HAVE_CNR_V30_LITE  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 30Lite"      FORCE)
    set(RKAIQ_HAVE_SHARP_V1 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 TRUE  CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33_LITE FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33Lite"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  TRUE  CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V23  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 23"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 23"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23_LITE  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23Lite"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   TRUE  CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_BLC_V32   FALSE  CACHE INTERNAL "Build rkaiq's BLC  version 32"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   FALSE CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_PDAF     TRUE  CACHE INTERNAL "Build rkaiq's PDAF"                FORCE)
    set(RKAIQ_HAVE_AF_V20   TRUE  CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   FALSE CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    set(RKAIQ_HAVE_AF_V32_LITE   FALSE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1 TRUE  CACHE INTERNAL "Build rkaiq's 3DLUT version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V1   TRUE  CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V2   FALSE CACHE INTERNAL "Build rkaiq's CCM version 2"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V10   TRUE CACHE INTERNAL "Build rkaiq's GAMMA version 10"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V11   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V10   TRUE CACHE INTERNAL "Build rkaiq's MERGE version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V11   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V12   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V10   TRUE CACHE INTERNAL "Build rkaiq's DRC version 10"       FORCE)
    set(RKAIQ_HAVE_DRC_V11   FALSE CACHE INTERNAL "Build rkaiq's DRC version 11"       FORCE)
    set(RKAIQ_HAVE_DRC_V12   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V12_LITE   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12 lite"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V10   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 10"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE version 11"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11_DUO   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11 DUO"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V12   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 12"       FORCE)
    set(RKAIQ_HAVE_DEGAMMA_V1   TRUE CACHE INTERNAL "Build rkaiq's DEGAMMA version 1"       FORCE)
    set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
    set(RKAIQ_HAVE_WDR_V1   TRUE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
    set(RKAIQ_HAVE_FEC_V10  FALSE  CACHE INTERNAL "Build rkaiq's FEC version 10"    FORCE)
    set(RKAIQ_HAVE_CSM_V1   TRUE CACHE INTERNAL "Build rkaiq's CSM version 1"       FORCE)
    set(RKAIQ_HAVE_CGC_V1   TRUE CACHE INTERNAL "Build rkaiq's CGC version 1"       FORCE)
    set(RKAIQ_HAVE_AE_V1   TRUE CACHE INTERNAL "Build rkaiq's AE version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V1   TRUE CACHE INTERNAL "Build rkaiq's DEBAYER version 1"       FORCE)
	set(RKAIQ_HAVE_DEBAYER_V2   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2_LITE   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2 lite"       FORCE)
    set(RKAIQ_HAVE_LSC_V1   TRUE CACHE INTERNAL "Build rkaiq's LSC version 1"       FORCE)
    set(RKAIQ_HAVE_LSC_V2   FALSE CACHE INTERNAL "Build rkaiq's LSC version 2"       FORCE)
    set(RKAIQ_HAVE_LSC_V3   FALSE CACHE INTERNAL "Build rkaiq's LSC version 3"       FORCE)
    set(RKAIQ_HAVE_DPCC_V1   TRUE CACHE INTERNAL "Build rkaiq's DPCC version 1"       FORCE)
    set(RKAIQ_HAVE_ACP_V10   TRUE CACHE INTERNAL "Build rkaiq's ACP version 10"       FORCE)
    set(RKAIQ_HAVE_AIE_V10   TRUE CACHE INTERNAL "Build rkaiq's AIE version 10"       FORCE)
    set(RKAIQ_HAVE_ASD_V10   FALSE CACHE INTERNAL "Build rkaiq's ASD version 10"       FORCE)
elseif (RKAIQ_ISP_VERSION STREQUAL "20")
    set(RKAIQ_HAVE_AWB_V20  TRUE  CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  FALSE CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_AWB_V32  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32"      FORCE)
    set(RKAIQ_HAVE_AWB_V32LT  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32Lite"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   TRUE  CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   FALSE CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   TRUE  CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   TRUE  CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V03  FALSE CACHE INTERNAL "Build rkaiq's CAC version 03"      FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_CAC_V11  FALSE CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V2   FALSE CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   FALSE CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_YNR_V22  FALSE CACHE INTERNAL "Build rkaiq's YNR version 22"      FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   FALSE CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   FALSE CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_CNR_V30  FALSE CACHE INTERNAL "Build rkaiq's CNR version 30"      FORCE)
    set(RKAIQ_HAVE_CNR_V30_LITE  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 30Lite"      FORCE)
    set(RKAIQ_HAVE_SHARP_V1 TRUE  CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33_LITE FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33Lite"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V23  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 23"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 23"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23_LITE  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23Lite"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   TRUE  CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_BLC_V32   FALSE  CACHE INTERNAL "Build rkaiq's BLC  version 32"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   TRUE  CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_PDAF     FALSE CACHE INTERNAL "Build rkaiq's PDAF"                FORCE)
    set(RKAIQ_HAVE_AF_V20   FALSE CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   FALSE CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    set(RKAIQ_HAVE_AF_V32_LITE   FALSE CACHE INTERNAL "Build rkaiq's AF version 32 lite"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1   TRUE CACHE INTERNAL "Build rkaiq's 3DLUT version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V1   TRUE CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V2   FALSE CACHE INTERNAL "Build rkaiq's CCM version 2"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V10   TRUE CACHE INTERNAL "Build rkaiq's GAMMA version 10"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V11   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V10   TRUE CACHE INTERNAL "Build rkaiq's MERGE version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V11   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V12   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V10   FALSE CACHE INTERNAL "Build rkaiq's DRC version 10"       FORCE)
    set(RKAIQ_HAVE_DRC_V11   FALSE CACHE INTERNAL "Build rkaiq's DRC version 11"       FORCE)
    set(RKAIQ_HAVE_DRC_V12   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V12_LITE   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12 lite"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V10   TRUE CACHE INTERNAL "Build rkaiq's DEHAZE version 10"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11_DUO   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11 DUO"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V12   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 12"       FORCE)
    set(RKAIQ_HAVE_DEGAMMA_V1   TRUE CACHE INTERNAL "Build rkaiq's DEGAMMA version 1"       FORCE)
    set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
    set(RKAIQ_HAVE_WDR_V1   TRUE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
    set(RKAIQ_HAVE_LDCH_V10  TRUE  CACHE INTERNAL "Build rkaiq's LDCH version 10"    FORCE)
    set(RKAIQ_HAVE_FEC_V10  TRUE  CACHE INTERNAL "Build rkaiq's FEC version 10"    FORCE)
    set(RKAIQ_HAVE_CSM_V1   TRUE CACHE INTERNAL "Build rkaiq's CSM version 1"       FORCE)
    set(RKAIQ_HAVE_CGC_V1   FALSE CACHE INTERNAL "Build rkaiq's CGC version 1"       FORCE)
    set(RKAIQ_HAVE_AE_V1   TRUE CACHE INTERNAL "Build rkaiq's AE version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V1   TRUE CACHE INTERNAL "Build rkaiq's DEBAYER version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2_LITE   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2 lite"       FORCE)
    set(RKAIQ_HAVE_LSC_V1   TRUE CACHE INTERNAL "Build rkaiq's LSC version 1"       FORCE)
    set(RKAIQ_HAVE_LSC_V2   FALSE CACHE INTERNAL "Build rkaiq's LSC version 2"       FORCE)
    set(RKAIQ_HAVE_LSC_V3   FALSE CACHE INTERNAL "Build rkaiq's LSC version 3"       FORCE)
    set(RKAIQ_HAVE_DPCC_V1   TRUE CACHE INTERNAL "Build rkaiq's DPCC version 1"       FORCE)
    set(RKAIQ_HAVE_ACP_V10   TRUE CACHE INTERNAL "Build rkaiq's ACP version 10"       FORCE)
    set(RKAIQ_HAVE_AIE_V10   TRUE CACHE INTERNAL "Build rkaiq's AIE version 10"       FORCE)
    set(RKAIQ_HAVE_ASD_V10   FALSE CACHE INTERNAL "Build rkaiq's ASD version 10"       FORCE)
else()
    set(RKAIQ_HAVE_AWB_V20  FALSE CACHE INTERNAL "Build rkaiq's AWB version 20"      FORCE)
    set(RKAIQ_HAVE_AWB_V21  FALSE CACHE INTERNAL "Build rkaiq's AWB version 21"      FORCE)
    set(RKAIQ_HAVE_AWB_V32  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32"      FORCE)
    set(RKAIQ_HAVE_AWB_V32LT  FALSE  CACHE INTERNAL "Build rkaiq's AWB version 32Lite"      FORCE)
    set(RKAIQ_HAVE_GIC_V1   FALSE CACHE INTERNAL "Build rkaiq's GIC version 1"       FORCE)
    set(RKAIQ_HAVE_GIC_V2   FALSE CACHE INTERNAL "Build rkaiq's GIC version 2"       FORCE)
    set(RKAIQ_HAVE_ORB_V1   FALSE CACHE INTERNAL "Build rkaiq's ORB version 1"       FORCE)
    set(RKAIQ_HAVE_EIS_V1   FALSE CACHE INTERNAL "Build rkaiq's EIS version 1"       FORCE)
    set(RKAIQ_HAVE_CAC_V03  FALSE CACHE INTERNAL "Build rkaiq's CAC version 03"      FORCE)
    set(RKAIQ_HAVE_CAC_V10  FALSE CACHE INTERNAL "Build rkaiq's CAC version 10"      FORCE)
    set(RKAIQ_HAVE_CAC_V11  FALSE CACHE INTERNAL "Build rkaiq's CAC version 11"      FORCE)
    set(RKAIQ_HAVE_YNR_V1   FALSE CACHE INTERNAL "Build rkaiq's YNR version 1"       FORCE)
    set(RKAIQ_HAVE_YNR_V2   FALSE CACHE INTERNAL "Build rkaiq's YNR version 2"       FORCE)
    set(RKAIQ_HAVE_YNR_V3   FALSE CACHE INTERNAL "Build rkaiq's YNR version 3"       FORCE)
    set(RKAIQ_HAVE_YNR_V22  FALSE CACHE INTERNAL "Build rkaiq's YNR version 22"      FORCE)
    set(RKAIQ_HAVE_UVNR_V1  FALSE CACHE INTERNAL "Build rkaiq's UVNR version 1"      FORCE)
    set(RKAIQ_HAVE_CNR_V1   FALSE CACHE INTERNAL "Build rkaiq's CNR version 1"       FORCE)
    set(RKAIQ_HAVE_CNR_V2   FALSE CACHE INTERNAL "Build rkaiq's CNR version 2"       FORCE)
    set(RKAIQ_HAVE_CNR_V30  FALSE CACHE INTERNAL "Build rkaiq's CNR version 30"      FORCE)
    set(RKAIQ_HAVE_CNR_V30_LITE  FALSE  CACHE INTERNAL "Build rkaiq's CNR version 30Lite"      FORCE)
    set(RKAIQ_HAVE_SHARP_V1 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 1"     FORCE)
    set(RKAIQ_HAVE_SHARP_V3 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 3"     FORCE)
    set(RKAIQ_HAVE_SHARP_V4 FALSE CACHE INTERNAL "Build rkaiq's SHARP version 4"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33 FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33"     FORCE)
    set(RKAIQ_HAVE_SHARP_V33_LITE FALSE  CACHE INTERNAL "Build rkaiq's SHARP version 33Lite"     FORCE)
    set(RKAIQ_HAVE_MFNR_V1  FALSE CACHE INTERNAL "Build rkaiq's MFNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V1  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 1"      FORCE)
    set(RKAIQ_HAVE_BAYERNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYERNR version 2"      FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V2  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 2"  FORCE)
    set(RKAIQ_HAVE_BAYER2DNR_V23  FALSE CACHE INTERNAL "Build rkaiq's BAYER2DNR version 23"  FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V2   FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 2"   FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23  FALSE CACHE INTERNAL "Build rkaiq's BAYERTNR version 23" FORCE)
    set(RKAIQ_HAVE_BAYERTNR_V23_LITE  FALSE  CACHE INTERNAL "Build rkaiq's BAYERTNR version 23Lite"   FORCE)
    set(RKAIQ_HAVE_GAIN_V1  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 1"      FORCE)
    set(RKAIQ_HAVE_GAIN_V2  FALSE CACHE INTERNAL "Build rkaiq's GAIN version 2"      FORCE)
    set(RKAIQ_HAVE_BLC_V1   FALSE CACHE INTERNAL "Build rkaiq's BLC  version 1"      FORCE)
    set(RKAIQ_HAVE_BLC_V32   FALSE  CACHE INTERNAL "Build rkaiq's BLC  version 32"      FORCE)
    set(RKAIQ_HAVE_ANR_V1   FALSE CACHE INTERNAL "Build rkaiq's ANR  version 1"      FORCE)
    set(RKAIQ_HAVE_AMD_V1   FALSE CACHE INTERNAL "Build rkaiq's AMD  version 1"      FORCE)
    set(RKAIQ_HAVE_PDAF     FALSE CACHE INTERNAL "Build rkaiq's PDAF"                FORCE)
    set(RKAIQ_HAVE_AF_V20   FALSE CACHE INTERNAL "Build rkaiq's AF version 20"       FORCE)
    set(RKAIQ_HAVE_AF_V30   FALSE CACHE INTERNAL "Build rkaiq's AF version 30"       FORCE)
    set(RKAIQ_HAVE_AF_V31   FALSE CACHE INTERNAL "Build rkaiq's AF version 31"       FORCE)
    set(RKAIQ_HAVE_3DLUT_V1 FALSE CACHE INTERNAL "Build rkaiq's 3DLUT version 1"     FORCE)
    set(RKAIQ_HAVE_CCM_V1   FALSE CACHE INTERNAL "Build rkaiq's CCM version 1"       FORCE)
    set(RKAIQ_HAVE_CCM_V2   FALSE CACHE INTERNAL "Build rkaiq's CCM version 2"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V10   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 10"       FORCE)
    set(RKAIQ_HAVE_GAMMA_V11   FALSE CACHE INTERNAL "Build rkaiq's GAMMA version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V10   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 10"       FORCE)
    set(RKAIQ_HAVE_MERGE_V11   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 11"       FORCE)
    set(RKAIQ_HAVE_MERGE_V12   FALSE CACHE INTERNAL "Build rkaiq's MERGE version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V10   FALSE CACHE INTERNAL "Build rkaiq's DRC version 10"       FORCE)
    set(RKAIQ_HAVE_DRC_V11   FALSE CACHE INTERNAL "Build rkaiq's DRC version 11"       FORCE)
    set(RKAIQ_HAVE_DRC_V12   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12"       FORCE)
    set(RKAIQ_HAVE_DRC_V12_LITE   FALSE CACHE INTERNAL "Build rkaiq's DRC version 12 lite"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V10   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 10"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V11_DUO   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 11 DUO"       FORCE)
    set(RKAIQ_HAVE_DEHAZE_V12   FALSE CACHE INTERNAL "Build rkaiq's DEHAZE version 12"       FORCE)
    set(RKAIQ_HAVE_DEGAMMA_V1   FALSE CACHE INTERNAL "Build rkaiq's DEGAMMA version 1"       FORCE)
    set(RKAIQ_HAVE_TMO_V1   FALSE CACHE INTERNAL "Build rkaiq's TMO version 1"       FORCE)
    set(RKAIQ_HAVE_WDR_V1   FALSE CACHE INTERNAL "Build rkaiq's WDR version 1"       FORCE)
    set(RKAIQ_HAVE_LDCH_V10  FALSE  CACHE INTERNAL "Build rkaiq's LDCH version 10"    FORCE)
    set(RKAIQ_HAVE_FEC_V10  FALSE  CACHE INTERNAL "Build rkaiq's FEC version 10"    FORCE)
    set(RKAIQ_HAVE_CSM_V1   FALSE CACHE INTERNAL "Build rkaiq's CSM version 1"       FORCE)
    set(RKAIQ_HAVE_CGC_V1   FALSE CACHE INTERNAL "Build rkaiq's CGC version 1"       FORCE)
    set(RKAIQ_HAVE_AE_V1   FALSE CACHE INTERNAL "Build rkaiq's AE version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V1   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 1"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2"       FORCE)
    set(RKAIQ_HAVE_DEBAYER_V2_LITE   FALSE CACHE INTERNAL "Build rkaiq's DEBAYER version 2 lite"       FORCE)
    set(RKAIQ_HAVE_LSC_V1   FALSE CACHE INTERNAL "Build rkaiq's LSC version 1"       FORCE)
    set(RKAIQ_HAVE_LSC_V2   FALSE CACHE INTERNAL "Build rkaiq's LSC version 2"       FORCE)
    set(RKAIQ_HAVE_LSC_V3   FALSE CACHE INTERNAL "Build rkaiq's LSC version 3"       FORCE)
    set(RKAIQ_HAVE_DPCC_V1   FALSE CACHE INTERNAL "Build rkaiq's DPCC version 1"       FORCE)
    set(RKAIQ_HAVE_ACP_V10   FALSE CACHE INTERNAL "Build rkaiq's ACP version 10"       FORCE)
    set(RKAIQ_HAVE_AIE_V10   FALSE CACHE INTERNAL "Build rkaiq's AIE version 10"       FORCE)
    set(RKAIQ_HAVE_ASD_V10   FALSE CACHE INTERNAL "Build rkaiq's ASD version 10"       FORCE)
endif()
