export ROOT_DIR:=$(CURDIR)/
export BUILD_SYSTEM:=$(CURDIR)/build_system/
export BUILD_OUTPUT_STATIC_LIBS:=$(CURDIR)/build/lib/
export BUILD_OUPUT_EXTERNAL_LIBS:=$(CURDIR)/ext/rkisp/usr/lib
export BUILD_OUPUT_RKISP_LIBS:=$(CURDIR)/ext/rkisp/lib
export BUILD_OUPUT_GSTREAMER_LIBS:=$(CURDIR)/ext/rkisp/usr/lib/gstreamer-1.0
export BUILD_OUPUT_SHARED_LIBS:=$(CURDIR)/build/lib/
export BUILD_OUTPUT_STATIC_OBJS:=$(CURDIR)/build/obj/static/
export BUILD_OUTPUT_SHARED_OBJS:=$(CURDIR)/build/obj/shared/
export BUILD_OUTPUT_BIN:=$(CURDIR)/build/bin/
export STATIC_LIB_SUFFIX:=.a
export SHARED_LIB_SUFFIX:=.so

export CLEAR_VARS:= $(BUILD_SYSTEM)/clear_vars.mk
export BUILD_STATIC_LIBRARY:=$(BUILD_SYSTEM)/build_static_library.mk
export BUILD_SHARED_LIBRARY:=$(BUILD_SYSTEM)/build_shared_library.mk
export BUILD_EXECUTABLE:=$(BUILD_SYSTEM)/build_executable.mk
export allSubdirMakefiles:=$(BUILD_SYSTEM)/definitions.mk
export TARGET_GCC:=$(CROSS_COMPILE)gcc
export TARGET_GPP:=$(CROSS_COMPILE)g++
export TARGET_AR:=$(CROSS_COMPILE)ar
export TARGET_LD:=$(CROSS_COMPILE)ld

$(shell mkdir -p $(BUILD_OUTPUT_STATIC_LIBS))
$(shell mkdir -p $(BUILD_OUPUT_SHARED_LIBS))
$(shell mkdir -p $(BUILD_OUTPUT_STATIC_OBJS))
$(shell mkdir -p $(BUILD_OUTPUT_SHARED_OBJS))
$(shell mkdir -p $(BUILD_OUTPUT_BIN))

define quiet-cmd-echo-build
    ${Q}echo "  [$1]  $2"
endef
