#include "rk_aiq.h"
#include "rk_aiq_comm.h"
#include "common/rk-isp39-config.h"
#include "uAPI2/rk_aiq_user_api2_isp39.h"
#include "rk_aiq_isp39_modules.h"

#include "range_check.h"
#include "rk_aiq_module_btnr40.c"
#include "rk_aiq_module_ynr34.c"
#include "rk_aiq_module_cnr34.c"
#include "rk_aiq_module_sharp34.c"
#include "rk_aiq_module_drc40.c"
#include "rk_aiq_module_blc30.c"
#include "rk_aiq_module_dpcc21.c"
