#include "cam_types.h"
using namespace std;

const char RK_HAL_FMT_STRING::HAL_FMT_STRING_NV12[] = "nv12";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_NV21[] = "nv21";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_YVU420[] = "yvu420";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_RGB565[] = "rgb565";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_RGB32[] = "rgb32";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_YUV422P[] = "yuv422p";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_NV16[] = "nv16";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_YUYV[] = "yuyv";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_JPEG[] = "jpeg";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_MJPEG[] = "mjpeg";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_H264[] = "h264";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_Y8[] = "y8";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_Y10[] = "y10";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_Y12[] = "y12";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_SBGGR10[] = "SBGGR10";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_SGBRG10[] = "SGBRG10";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_SGRBG10[] = "SGRBG10";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_SRGGB10[] = "SRGGB10";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_SBGGR8[] = "SBGGR8";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_SGBRG8[] = "SGBRG8";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_SGRBG8[] = "SGRBG8";
const char RK_HAL_FMT_STRING::HAL_FMT_STRING_SRGGB8[] = "SRGGB8";




